# 1.requests 모듈 : HTTP프로토콜을 사용할 수 있게 해주는 모듈
* requsest모듈 사용설명서
[requests](https://requests.readthedocs.io/en/latest/user/quickstart/)

# 2. requests 모듈 설치
* conda install requests
* pip install requests

# 3. requests 모듈 사용법

* 1) 모듈 불러오기: import requests
* 2) url 변수에 저장
* 3) url 파라미터
    * payload = {파라미터1 : value, 파라미터2 : value}
* 4) headers
    * headers = {key : value}
* 5) HTTP 요청 보내기 get, post
    * get: r = requests.get(url, params=payload, headers=headers)
    * post: r = requests.post(url, data={key:value})
* 6) 만들어진 url 확인: print(r, url)
* 7) 응답 코드 확인: print(r.status_code)
* 8) 응답 요소 출력: r.text, r.content, r.json()

# requests 모듈로 페이지만 가져오기

In [13]:
import requests
url = "https://openapi.naver.com/v1/search/blog.json"
Client_Id = "uk7phJIAYBDY5KptX5ev"
Client_Secret = "cnGUx6svh_"
payload = dict(query='핀테크', display=10, start=1, sort="sim")
headers = {"X-Naver-Client-Id" : Client_Id, 
           "X-Naver-Client-Secret" : Client_Secret}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=10&start=1&sort=sim
200

{'lastBuildDate': 'Tue, 01 Apr 2025 23:29:44 +0900',
 'total': 456373,
 'start': 1,
 'display': 10,
 'items': [{'title': '[<b>핀테크</b>] 2024년 <b>핀테크</b> 업계 결산: 놀라운 3가지 변화',
   'link': 'https://blog.naver.com/xoom777/223708685044',
   'description': '동안 <b>핀테크</b> 업계에는 예상치 못한 변화의 바람이 불었습니다. 한동안 주춤했던 트렌드가... 올 한 해 <b>핀테크</b> 업계를 뜨겁게 달군 3가지 트렌드에 대해 자세히 살펴보겠습니다. 암호화폐의 귀환, 기관... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241229'},
  {'title': '<b>핀테크</b> 투자 후기',
   'link': 'https://blog.naver.com/kan1687/223812724931',
   'description': '<b>핀테크</b> 투자, 아직도 망설이고 계신가요?  여러분 혹시 이런 고민 해보신 적 있나요? &quot;<b>핀테크</b> 분야가 떴다는데, 지금 시작해도 괜찮을까? 좀 더 상황을 지켜봐야 하나?&quot; 사실 이런 생각은 투자를 고민하는 우리... ',
   'bloggername': '우정잉♥',
   'bloggerlink': 'blog.naver.com/kan1687',
   'postdate': '20250329'},
  {'title': '[인사이트 캠퍼스] 2025 동계 <b>핀테크</b> 캠프 (with 전주대학교... ',
   'link': 'https://blog.naver.com/fininsight/223734638126',
   'description': '전주대학교 친구들이 직접 여의도까지 방문하여 <b>핀테크</b>(FinTech)의 세계를 탐구할 기회를 가질 수... <b>핀테크</b>의 개념부터 해당 기술을 적용하는 사업 분야 그리고 앞으로의 트렌드까지 현업자의 시선에서 면밀하게... ',
   'bloggername': '핀인사이트 (Fininsight)',
   'bloggerlink': 'blog.naver.com/fininsight',
   'postdate': '20250122'},
  {'title': '[AI <b>핀테크</b>] AI와 빅데이터로 금융 시장을 재편하는 <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/jangpung_/223765345858',
   'description': '이제 대출도 AI가 하는 시대 출처 : 파가야 테크놀러지스 홈페이지 금융과 기술이 만나는 <b>핀테크</b>... 제공하는 <b>핀테크</b> 기업으로, 현재 미국, 이스라엘, 케이맨 제도 등여러나라에서 사업을 진행하고 있다.... ',
   'bloggername': '낭만을 꿈꾸는 일상',
   'bloggerlink': 'blog.naver.com/jangpung_',
   'postdate': '20250218'},
  {'title': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대',
   'link': 'https://blog.naver.com/jaso_/223736810791',
   'description': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대 IPAY ETF는 모바일 결제 산업에 투자하는 ETF로 <b>핀테크</b>관련주라고 보시면 되는데요. 이번 포스팅에선 IPAY <b>핀테크</b>관련주 ETF, 투자수익률, 미국 CBDC... ',
   'bloggername': '미국주식 퍼주마',
   'bloggerlink': 'blog.naver.com/jaso_',
   'postdate': '20250130'},
  {'title': '맨틀 MNT 코인 디파이 <b>핀테크</b> 서비스 소개',
   'link': 'https://blog.naver.com/tmglove/223781181469',
   'description': '웹2와 웹3을 아우르며 기관과 개인 그리고 리테일을 위한 다양한 <b>핀테크</b> 서비스 출시를 준비하고 있다고 하는데요. 그래서 오늘은 MNT 코인의 디파이 <b>핀테크</b> 서비스에 대해 알아보겠습니다. <b>핀테크</b>로... ',
   'bloggername': 'Hello-',
   'bloggerlink': 'blog.naver.com/tmglove',
   'postdate': '20250302'},
  {'title': '[<b>핀테크</b> 리더] # 2024 금융위원회 선정 10대 기업 _ 1편',
   'link': 'https://blog.naver.com/koreafintech/223675560515',
   'description': "[<b>핀테크</b> 리더] ⭐ # 2024 금융위원회 선정 10대 기업 _ 1편 금융위원회는 &lt;코리아 <b>핀테크</b> 위크 2024&gt;에서 작년에 이어 'K-Fintech 30' 프로젝트에 선정된 유망 <b>핀테크</b> 기업 10개사를 발굴하여 소개하였습니다. 'K... ",
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241128'},
  {'title': '맨틀 네트워크 코인 MNT <b>핀테크</b> 서비스 등장',
   'link': 'https://blog.naver.com/ghfjvb465/223781841217',
   'description': '맨틀네트워크 코인 <b>핀테크</b>와 크립토 경계 허물기 소개, 시세, 전망 코하! 경제적 자유 얻기... 이번 포스팅에서는 맨틀네트워크 코인 MNT의 <b>핀테크</b> 분야 진출 서비스 소개에 대한 내용을 함께 알아보는... ',
   'bloggername': '노마드신지테의 경제적자유얻기 챌린지',
   'bloggerlink': 'blog.naver.com/ghfjvb465',
   'postdate': '20250303'},
  {'title': '맨틀 코인 전망 디파이를 넘어 <b>핀테크</b>로 확장하는 미래',
   'link': 'https://blog.naver.com/duswnswlstlf/223782041308',
   'description': 'WEB2와 WEB3를 아우르는 기업들이 늘어나고 있지만 현실은 <b>핀테크</b> 기업들이 크립토 산업에 진출할 뿐, 크립토 기업들이 <b>핀테크</b> 사업으로 진출한 경우는 없네요. 가끔은 왜 WEB3 기업들은 디파이를 넘어서 WEB2의... ',
   'bloggername': '이기사 블로그',
   'bloggerlink': 'blog.naver.com/duswnswlstlf',
   'postdate': '20250303'},
  {'title': '테크놀로지스(PGY): AI 기반 대출 혁신의 주목받는 <b>핀테크</b> 기업',
   'link': 'https://blog.naver.com/an5217/223810108719',
   'description': '최근 <b>핀테크</b> 업계에서 주목받는 기업 **파가야 테크놀로지스(NASDAQ:PGY)**가 투자자와 애널리스트들... 제공하는 <b>핀테크</b> 기업입니다. 머신러닝 알고리즘을 통해 개인 대출, 자동차 대출, POS(Point-of-Sale)... ',
   'bloggername': '오늘 하루도 절도있고 검소하게',
   'bloggerlink': 'blog.naver.com/an5217',
   'postdate': '20250326'}]}

* 모든 검색 결과를 가져오기 위해서는 여러페이지 정보를 수집
* 전체 결과 / 1페이지 표시 개수 + 1 = 전체 페이지 수
* start 부분 + 1페이지 표시 개수 = 다음 페이지 데이터 수집 가능
* 반복문을 이용해서 start에 100씩 더해서 최대 1000이 되도록 하면 최대한 많은 데이터 수집 가능

In [14]:
start_num2 = 1
for s_num in range(11):
    if start_num2 < 901: 
        print(start_num2)
        start_num2 += 100
    elif start_num2 == 901:
        print(start_num2)
        start_num2 += 99

1
101
201
301
401
501
601
701
801
901

In [15]:
import requests
start_num = 1
result_json = []
for page in range(11):
    url = "https://openapi.naver.com/v1/search/blog.json"
    Client_Id = "uk7phJIAYBDY5KptX5ev"
    Client_Secret = "cnGUx6svh_"
    payload = dict(query='핀테크', display=100, start=start_num, sort="sim")
    headers = {"X-Naver-Client-Id" : Client_Id, 
               "X-Naver-Client-Secret" : Client_Secret}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response = r.json()
    result_json.append(response)
    if start_num < 901: 
        start_num += 100
    elif start_num == 901:
        start_num += 99

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200

In [16]:
result_json[0].keys()

dict_keys(['lastBuildDate', 'total', 'start', 'display', 'items'])

In [17]:
pages = result_json[0]['total'] // result_json[0]['display'] + 1 # 페이지 수
pages

4564

In [6]:
start_num = 1
response_json2 = []
for page in range(pages):
    url = "https://openapi.naver.com/v1/search/blog.json"
    Client_Id = "uk7phJIAYBDY5KptX5ev"
    Client_Secret = "cnGUx6svh_"
    payload = dict(query='핀테크', display=100, start=start_num, sort="sim")
    headers = {"X-Naver-Client-Id" : Client_Id, 
               "X-Naver-Client-Secret" : Client_Secret}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response = r.json()
    pages = response['total'] // response['display'] + 1
    response_json2.append(response)
    if start_num == 1000:
        break
    if start_num < 901: 
        start_num += 100
    elif start_num == 901:
        start_num += 99

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200

In [7]:
response_json2[1]

{'lastBuildDate': 'Tue, 01 Apr 2025 23:28:03 +0900',
 'total': 456371,
 'start': 101,
 'display': 100,
 'items': [{'title': '[ 업스타트 홀딩스 ] AI와 금융의 만남,<b>핀테크</b> 대출 시장을... ',
   'link': 'https://blog.naver.com/gopagi7/223814284723',
   'description': '개요 업스타트 홀딩스(티커: UPST)는 AI 기반 대출 플랫폼을 운영하는 <b>핀테크</b> 기업으로, 전통적인... ㆍ규제 및 경쟁 심화 → <b>핀테크</b> 기업 및 전통 금융기관과 경쟁. 5. 향후 전망 ㆍAI 모델 고도화 → 신용... ',
   'bloggername': '사고싶은주식',
   'bloggerlink': 'blog.naver.com/gopagi7',
   'postdate': '20250329'},
  {'title': 'EBS 입트영 해외여행을 편리하게 해 주는 <b>핀테크</b> 기술',
   'link': 'https://blog.naver.com/jjang03/223680514029',
   'description': '2024 11월 27일 EBS 입트영 사연은 <b>핀테크</b> 기술을 이용하여 환전등을 할 필요 없이 편리하게 해외여행을 할 수 있는 정보를 주고 있습니다. 약간의 현금은 필요할수도 있겠지만 정말... ',
   'bloggername': '베티의 매일영어 쉬운영어',
   'bloggerlink': 'blog.naver.com/jjang03',
   'postdate': '20241203'},
  {'title': '신규 상장 더즌 <b>핀테크</b> B2B 기업용 금융통신망 쉿 쉿 조용 조용',
   'link': 'https://blog.naver.com/2yongki/223805949459',
   'description': '기업 개요 20017년 설립 기업용 금융 통신망 서비스를 제공하는 <b>핀테크</b> 업체 금융 인프라를 기반으로... ② 경쟁 심화: * <b>핀테크</b> 시장은 경쟁이 치열하며, 새로운 경쟁자의 등장 가능성도 있습니다. * 새로운... ',
   'bloggername': '행복한남 경제야놀자',
   'bloggerlink': 'blog.naver.com/2yongki',
   'postdate': '20250323'},
  {'title': '센트비, 2024 싱가포르 <b>핀테크</b> 페스티벌에서 혁신을 선보이다!',
   'link': 'https://blog.naver.com/sentbecorp/223662020356',
   'description': '센트비가 지난 11월 6일부터 8일까지 열린 2024 싱가포르 <b>핀테크</b> 페스티벌(Singapore Fintech Festival, SFF)에 참가해 큰 호응을 얻었습니다! 행사 기간 내내 센트비의 서비스를 글로벌 무대에 선보이며, <b>핀테크</b>... ',
   'bloggername': '글로벌 핀테크 솔루션, 센트비',
   'bloggerlink': 'blog.naver.com/sentbecorp',
   'postdate': '20241115'},
  {'title': 'BNK금융그룹, <b>핀테크</b> 랩 ‘Storage B’ 2기 참여기업 모집',
   'link': 'https://blog.naver.com/bnkfinancialgroup/223632936786',
   'description': 'BNK금융그룹이 우수한 기술력과 성장성을 갖춘 스타트업을 지원하기 위해 운영 중인 <b>핀테크</b> 랩... 현재 18개의 스타트업 및 <b>핀테크</b> 기업이 멤버로 참여하고 있습니다. 모집 대상은 지급결제, 데이터, 인공지능... ',
   'bloggername': 'BNK금융그룹 공식 블로그',
   'bloggerlink': 'blog.naver.com/bnkfinancialgroup',
   'postdate': '20241025'},
  {'title': '<b>핀테크</b> 기술이 이끄는 간편한 세상',
   'link': 'https://blog.naver.com/jjsbmh2/223795518211',
   'description': '<b>핀테크</b> 기술이 이끄는 간편한 세상 스마트폰 하나면 모든 결제와 송금이 가능한 시대다. 과거 금융... 몇 년 사이 금융(Finance)에 정보기술(Technology)을 결합한 <b>핀테크</b>(Fintech)가 급성장하며 이러한 변화가... ',
   'bloggername': '광클하는 빌런',
   'bloggerlink': 'blog.naver.com/jjsbmh2',
   'postdate': '20250314'},
  {'title': "녹색 금융과 기술의 만남 '그린 <b>핀테크</b>', 제대로 정착하려면?",
   'link': 'https://blog.naver.com/wisdot_official/223803754821',
   'description': "자리잡으면서 '그린<b>핀테크</b>'가 주목을 받고 있다. 하지만 글로벌 투자흐름과는 달리 국내에서는 아직... 20일 금융업계에 따르면 그린<b>핀테크</b>란 디지털 금융 서비스를 통해 환경 보호, 탄소 저감, 그리고 사회적... ",
   'bloggername': '위즈경제',
   'bloggerlink': 'blog.naver.com/wisdot_official',
   'postdate': '20250320'},
  {'title': '<b>핀테크</b> 개발자가 되기 위해 필요한 역량과 취업 준비 방법',
   'link': 'https://blog.naver.com/alsldd3/223812739187',
   'description': '<b>핀테크</b> 개발자가 되기 위해 필요한 역량과 취업 준비 방법 안녕하세요. 적어보았다입니다. 최근 금융과 기술이 융합된 <b>핀테크</b> 산업이 빠르게 성장하면서, <b>핀테크</b> 개발자에 대한 수요도 증가하고 있는데요.... ',
   'bloggername': '✍적어보았다.✍',
   'bloggerlink': 'blog.naver.com/alsldd3',
   'postdate': '20250328'},
  {'title': "[News] 이롬넷 '페이버스' 코리아 <b>핀테크</b> 위크 2024 참가 현장",
   'link': 'https://blog.naver.com/payverse/223594970064',
   'description': '코리아 <b>핀테크</b> 위크 2024 - 이롬넷 페이버스 부스 안녕하세요, PayVerse입니다! 지난 8월 27일 ~ 29일 3일간, 동대문 디자인 플라자(DDP)에서 열린 코리아 <b>핀테크</b> 위크 2024(Korea Fintech Week 2024)에 이롬넷이... ',
   'bloggername': '페이버스(PayVerse)',
   'bloggerlink': 'blog.naver.com/payverse',
   'postdate': '20240924'},
  {'title': '[슬기로운 <b>핀테크</b> 생활] # 8편... 포인트도 적립하는 <b>핀테크</b>!',
   'link': 'https://blog.naver.com/koreafintech/223509421687',
   'description': '[슬기로운 <b>핀테크</b> 생활]  #8 - 친환경 그린 앱테크: 환경보호로 포인트도 적립하는 <b>핀테크</b>! 오늘은 <b>핀테크</b> 서비스 중, 하나뿐인 지구를 지키기 위해 일상에서 기후행동을 실천하면 금융 혜택을 제공하는... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20240711'},
  {'title': "[ 페이업뉴스] 페이업이 '제 9회 한경 <b>핀테크</b>대상' 테크 분야... ",
   'link': 'https://blog.naver.com/payupkorea/223639535347',
   'description': '페이업이 [제 9회 한경 <b>핀테크</b>대상] 테크분야 간편결제 부문 최우수상을 수상했어요! 축하할 소식은 바로 페이업 주식회사가 [제 9회 한경 <b>핀테크</b> 대상] 테크분야 간편결제 부문에서 최우수상을 받았다는... ',
   'bloggername': '페이업 공식블로그',
   'bloggerlink': 'blog.naver.com/payupkorea',
   'postdate': '20241030'},
  {'title': '[기자단 뉴스] <b>핀테크</b>큐브 입주기업을 소개합니다!',
   'link': 'https://blog.naver.com/koreafintech/223546249892',
   'description': "<b>핀테크</b>큐브 입주기업을 소개합니다! 제12기 대학생 기자단 이유진 <b>핀테크</b> 큐브는 어떤 곳인가요? '<b>핀테크</b> 스케일업 추진전략' (19.12 금융위원회)의 일환으로 <b>핀테크</b> 스타트업의 스케일업 및 국내/외 진출을... ",
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20240813'},
  {'title': '2024 APEC 중소기업 디지털 금융 및 <b>핀테크</b> 혁신 포럼 개최!',
   'link': 'https://blog.naver.com/sbcblog/223667246424',
   'description': '중소벤처기업진흥공단입니다 2024 APEC 중소기업 디지털 금융 및 <b>핀테크</b> 혁신 포럼을 개최합니다!  2024 APEC 중소기업 디지털 금융 및 <b>핀테크</b> 혁신 포럼은? APEC 및 중소벤처기업부와 협력하여... ',
   'bloggername': '중소벤처기업진흥공단',
   'bloggerlink': 'blog.naver.com/sbcblog',
   'postdate': '20241120'},
  {'title': '<b>핀테크</b> 뜻 기업 종류 산업 사례 장단점 알아보자',
   'link': 'https://blog.naver.com/franksong0030/223776691078',
   'description': '최근 금융과 기술의 융합이 빠르게 진행되면서 ‘<b>핀테크</b>(FinTech)’라는 용어가 우리 생활 속 깊숙이 자리 잡고 있다. 모바일 결제부터 블록체인, 인공지능을 활용한 자산 관리까지 <b>핀테크</b> 산업은 다양한... ',
   'bloggername': 'Franky, IT Story',
   'bloggerlink': 'blog.naver.com/franksong0030',
   'postdate': '20250303'},
  {'title': '<b>핀테크</b> 거인들의 숨은 이야기: 금융 혁명의 현재와 미래',
   'link': 'https://blog.naver.com/qbaseoam69/223814682728',
   'description': '그리고 <b>핀테크</b>는 돈을 바꾼다.” – 익명의 금융 전문가 한 번쯤 이런 경험이 있을 것이다. 카페에서... 이것이 바로 <b>핀테크</b>가 가져온 혁신이다. 하지만, 우리가 매일 사용하는 이 시스템 뒤에는 어떤 기업들이... ',
   'bloggername': '뽀빠이',
   'bloggerlink': 'blog.naver.com/qbaseoam69',
   'postdate': '20250330'},
  {'title': '지급결제 시스템 혁신과 미래 변화 <b>핀테크</b>의 역할과 과제',
   'link': 'https://blog.naver.com/makenah_bismagas/223761703712',
   'description': '지급결제 시스템 혁신과 미래 변화 <b>핀테크</b>의 역할과 과제 지급결제는 현대 경제의 혈액과 같아요. 온라인 쇼핑부터 해외 송금까지, 우리 삶에 깊숙이 들어와 있죠. <b>핀테크</b> 기술 덕분에 지급결제 시장은 더욱... ',
   'bloggername': '오늘 점심은 스시, 일등석 타고 오사카로 슝=3',
   'bloggerlink': 'blog.naver.com/makenah_bismagas',
   'postdate': '20250215'},
  {'title': '특허등록절차, 어플 시스템 <b>핀테크</b> 등 확실한 보호 TIP',
   'link': 'https://blog.naver.com/woocat0204/223448230394',
   'description': '표제에서 말씀드린 것과 같이 어플, 시스템, <b>핀테크</b> 기술을 확실하게 보호하고 싶다면 어떻게 해야... 어플 시스템 <b>핀테크</b> 기술은 특허권으로 - 요즘 뜨는 기술에 대한 독점권을 확보하고 싶을 때 - 이노비즈... ',
   'bloggername': '[테헤란 특허 비즈니스 센터]',
   'bloggerlink': 'blog.naver.com/woocat0204',
   'postdate': '20240516'},
  {'title': '한국에서 미국으로 달러 송금시, 주요 은행 및 <b>핀테크</b> 수수료 비교',
   'link': 'https://blog.naver.com/detail-/223729561262',
   'description': '다음으로 카카오뱅크 및 <b>핀테크</b>업체 등에서 주로 사용하는 ACH 방식의 경우, 미국 은행에서... 등의 <b>핀테크</b> 송금업체 등에서도 저렴한 수수료로 ACH 방식을 제공하므로, 이 경우에는 참 다양한 선택지가... ',
   'bloggername': '목동 자녀 교육의 모든 것',
   'bloggerlink': 'blog.naver.com/detail-',
   'postdate': '20250118'},
  {'title': '[기자단 뉴스] 이런 <b>핀테크</b>는 어떤가요?',
   'link': 'https://blog.naver.com/koreafintech/223517010400',
   'description': '로보어드바이저 이런 <b>핀테크</b>는 어떤가요? 12기 대학생 기자단 남현영 로보어드바이저란? 인공지능과... 기대됨 <b>핀테크</b> 분야는 기술과 금융이 결합하여 다양한 혁신적인 아이디어가 나올 수 있는 영역! 오늘... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20240718'},
  {'title': '서울<b>핀테크</b>위크2024 - 스마트라이프를 실천하는 금융중심지... ',
   'link': 'https://blog.naver.com/120108julie/223627809035',
   'description': '안녕하세요 [서울<b>핀테크</b>위크2024 서포터즈] 서주희입니다. 10월 8일 행사가 성공적으로 마무리 되었습니다! 행사 내용과 후기를 전달하고자 기록합니다. 우리나라 <b>핀테크</b> 미래에 대한 건설적인 대화가 오간... ',
   'bloggername': '생각 상자',
   'bloggerlink': 'blog.naver.com/120108julie',
   'postdate': '20241021'},
  {'title': '[<b>핀테크</b>] 프랑스 <b>핀테크</b> 리디아, 새로운 디지털 뱅킹 앱... ',
   'link': 'https://blog.naver.com/xoom777/223708662769',
   'description': 'com/2024/05/french-fintech-lydia-launches-digital-banking-app-sumeria/ lydia 프랑스의 <b>핀테크</b> 스타트업 리디아가... 리디아의 변신, 유럽 <b>핀테크</b> 시장의 새로운 바람될까 P2P 송금 앱에서 출발해 종합 금융 플랫폼으로... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241229'},
  {'title': '20대 29%는 ‘인터넷은행 주거래’… <b>핀테크</b> 침투 주목',
   'link': 'https://blog.naver.com/serve_as_servant/223789705924',
   'description': '및 주거래 이유’ 보고서에 따르면 성인 금융소비자 10명 중 8명(80.7%)은 여전히 주거래 금융사로 은행을 이용한다고 답했다. 토스 등 <b>핀테크</b> 업체를 주로 이용한다는 소비자는 9.8%, 증권사는 4.4%였다. - 세계일보',
   'bloggername': '아름다운 동행',
   'bloggerlink': 'blog.naver.com/serve_as_servant',
   'postdate': '20250309'},
  {'title': '잡아야 할 AI 기술주 2선 XYZ DDOG 주가(feat.<b>핀테크</b>, 클라우드)',
   'link': 'https://blog.naver.com/vamosprimavera/223811441218',
   'description': '미국주식 추천, 급등 전 잡아야 할 AI 기술주 2선 XYZ DDOG 주가(feat.<b>핀테크</b>, 클라우드) 2025년, AI... 블록(Block): AI로 무장한 <b>핀테크</b> 플랫폼 블록은 과거 ‘스퀘어(Square)’로 알려졌던 기업으로, 간편... ',
   'bloggername': '뽜모스 for a better day',
   'bloggerlink': 'blog.naver.com/vamosprimavera',
   'postdate': '20250327'},
  {'title': '[코리아 <b>핀테크</b>위크 2024] DDP에서 열린 <b>핀테크</b> 박람회 탐방기!',
   'link': 'https://blog.naver.com/metaerim/223562937348',
   'description': '안녕하세요~ 오늘은 동대문디자인플라자에서 열린 우리나라 대표 <b>핀테크</b> 박람회인 코리아 <b>핀테크</b>위크 2024에 다녀온 얘기를 해볼까해요! 코리아 <b>핀테크</b>위크 2024 소개를 하기 전 많은 분들이 <b>핀테크</b>에 대해... ',
   'bloggername': '탦이 사는 이야기',
   'bloggerlink': 'blog.naver.com/metaerim',
   'postdate': '20240827'},
  {'title': '<b>핀테크</b> 조기 진입: 성공과 실패 사례',
   'link': 'https://blog.naver.com/lcnkksrw7009f6/223807944054',
   'description': '안녕하세요, <b>핀테크</b> 산업에 관심 있는 여러분! 오늘은 <b>핀테크</b> 분야에서 조기 진입의 중요성과 그로 인해 발생할 수 있는 성공과 실패 사례에 대해 이야기해보겠습니다. <b>핀테크</b>, 즉 금융과 기술의 융합은 최근 몇... ',
   'bloggername': '포근한 나의 방',
   'bloggerlink': 'blog.naver.com/lcnkksrw7009f6',
   'postdate': '20250401'},
  {'title': "[ 페이업 뉴스] 페이업이 '코리아<b>핀테크</b>위크 2024'에 참가했어요!",
   'link': 'https://blog.naver.com/payupkorea/223577892255',
   'description': '페이업은 이번 6번째로 맞이한 코리아 <b>핀테크</b> 위크 2024에 참가하게 되었는데요. 동대문 디지털플라자 DDP에서 총 3일 동안 열렸습니다. 이번 코리아 <b>핀테크</b> 위크는 어떤 주제로 개최되었는지, 페이업은... ',
   'bloggername': '페이업 공식블로그',
   'bloggerlink': 'blog.naver.com/payupkorea',
   'postdate': '20240909'},
  {'title': '<b>핀테크</b> 산업의 최신 동향과 변화',
   'link': 'https://blog.naver.com/joufpo5027b5/223807413605',
   'description': '오늘은 <b>핀테크</b> 산업의 최신 동향과 변화에 대해 살펴보겠습니다. <b>핀테크</b>는 금융과 기술의 융합으로, 혁신적인 서비스와 솔루션을 제공하며, 전통적인 금융 시스템을 크게 변화시키고 있습니다. 최근 몇 년간... ',
   'bloggername': '어디선가 고백하다',
   'bloggerlink': 'blog.naver.com/joufpo5027b5',
   'postdate': '20250401'},
  {'title': '<b>핀테크</b> 혁신: 금융 서비스 변화와 미래 전망, 과제 분석',
   'link': 'https://blog.naver.com/occupafati13914/223816558770',
   'description': '<b>핀테크</b> 혁신: 금융 서비스 변화와 미래 전망, 과제 분석 <b>핀테크</b>는 금융과 기술이 만나 탄생한 혁신적인 분야로, 우리의 금융 생활을 편리하고 효율적으로 바꿔주고 있어요. 모바일 결제부터 인공지능 기반 자산... ',
   'bloggername': '율곡 이이',
   'bloggerlink': 'blog.naver.com/occupafati13914',
   'postdate': '20250331'},
  {'title': '<b>핀테크</b> 생태계에서 스타트업의 역할',
   'link': 'https://blog.naver.com/levmj0730d1/223808670452',
   'description': '오늘은 <b>핀테크</b> 생태계에서 스타트업이 어떤 역할을 하고 있는지에 대해 이야기해보겠습니다. <b>핀테크</b>는 빠르게 변화하는 금융 산업의 혁신을 이끄는 중요한 요소로 자리잡고 있으며, 특히 스타트업의 기여가... ',
   'bloggername': '편안한 쉼의 시간',
   'bloggerlink': 'blog.naver.com/levmj0730d1',
   'postdate': '20250401'},
  {'title': '<b>핀테크</b> 기업의 마케팅 전략 분석',
   'link': 'https://blog.naver.com/msedyh654e5/223808935169',
   'description': '오늘은 <b>핀테크</b>(Fintech) 기업들이 어떻게 효과적으로 마케팅 전략을 수립하고 실행하는지에 대해 알아보겠습니다. <b>핀테크</b> 산업은 금융 서비스와 기술의 융합으로 급격히 성장하고 있으며, 이에 따라 다양한... ',
   'bloggername': '구름을 향한 소망',
   'bloggerlink': 'blog.naver.com/msedyh654e5',
   'postdate': '20250331'},
  {'title': '만났다고? 코리아<b>핀테크</b>위크2024 방문툰 [금융프렌즈]',
   'link': 'https://blog.naver.com/blogfsc/223573310685',
   'description': "코리아 <b>핀테크</b> 위크 갔다왔어. 이건 거기서 받은 기념품들&quot; &quot;코리아 <b>핀테크</b> 위크?&quot; &quot;글로벌 <b>핀테크</b> 박람회인 '코리아 <b>핀테크</b> 위크 2024'가 8월 27일(수) ~ 29일(금)동안 서울 DDP에서 개최됐었거든!&quot; &quot;오, 이게... ",
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20240905'},
  {'title': '<b>핀테크</b>의 지속 가능성: 환경적 접근',
   'link': 'https://blog.naver.com/glzwgsg0181q6/223811286007',
   'description': '<b>핀테크</b>(FinTech)는 최근 몇 년 간 빠르게 성장하며 우리의 삶에 많은 변화를 가져왔습니다. 그러나 이러한 성장 뒤에 있는 환경적 영향에 대한 우려가 커지고 있습니다. 이번 글에서는 <b>핀테크</b>의 지속 가능성, 특히... ',
   'bloggername': '은은한 빛의 정원',
   'bloggerlink': 'blog.naver.com/glzwgsg0181q6',
   'postdate': '20250401'},
  {'title': '금융당국이 올해 열번째로 중소 <b>핀테크</b> 기업들과 소통했습니다.',
   'link': 'https://blog.naver.com/fss2009/223639577485',
   'description': '해당 간담회 같은 경우 중소 <b>핀테크</b> 기업들의 규제 관련 애로사항을 청취하고 답변을 제공하는 간담회인데요! 금융위원회와 금융감독원, 한국<b>핀테크</b>지원센터는 10월 28일 한화생명 드림플러스 강남센터에서... ',
   'bloggername': '금융감독원 공식 블로그',
   'bloggerlink': 'blog.naver.com/fss2009',
   'postdate': '20241030'},
  {'title': '전자금융공동망: <b>핀테크</b> 혁신의 기반, 과제와 미래 전망',
   'link': 'https://blog.naver.com/none6111/223815544876',
   'description': '전자금융공동망: <b>핀테크</b> 혁신의 기반, 과제와 미래 전망 전자금융공동망, <b>핀테크</b> 혁명의 숨은 주역이라고 불리는 이 시스템은 은행, 증권사, 카드사 같은 금융기관들이 서로 돈을 주고받을 수 있게 연결해주는... ',
   'bloggername': '창의적일상',
   'bloggerlink': 'blog.naver.com/none6111',
   'postdate': '20250331'},
  {'title': '금리 인하와 가계부채 및 <b>핀테크</b>에 대해 언급 - 2024년 12월 31일',
   'link': 'https://blog.naver.com/xoom777/223710817655',
   'description': '기술(<b>핀테크</b>) 등 태국 경제의 주요 현안에 대한 견해를 밝혔습니다. 이는 태국 경제의 현 상황과... <b>핀테크</b> 활성화로 금융 포용 확대 세타왓 총재는 <b>핀테크</b> 발전이 금융 혁신과 포용에 기여할 것으로... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241231'},
  {'title': '코리아 <b>핀테크</b> 위크 2024 성황리에 마무리되었습니다',
   'link': 'https://blog.naver.com/blogfsc/223590188553',
   'description': "<b>핀테크</b>와 인공지능, 금융의 미래를 열다 '코리아 <b>핀테크</b> 위크 2024'를 성황리에 마쳤습니다 ✅ 12,500명 이상 방문 (2023년 대비 약 17% 증가) ✅ 기업·기관 참여 109개 등 역대 최대 규모로 진행 코리아... ",
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20240920'},
  {'title': '‘서울 <b>핀테크</b> 위크 2024’ 데모데이, 프랙탈에프엔 우수기업... ',
   'link': 'https://blog.naver.com/little_buffett/223613562824',
   'description': "‘서울 <b>핀테크</b> 위크 2024’ 데모데이, 프랙탈에프엔 우수기업 선정 제2서울<b>핀테크</b>랩 데모데이, 프랙탈에프앤 수상 지난 10월 7일부터 3일간 진행되는 '서울 <b>핀테크</b> 위크 2024'에 우수한 성적의 <b>핀테크</b>... ",
   'bloggername': '리틀버핏 공식블로그',
   'bloggerlink': 'blog.naver.com/little_buffett',
   'postdate': '20241010'},
  {'title': '<b>핀테크</b>에서의 고객 피드백 활용 방안',
   'link': 'https://blog.naver.com/mrlsa2333m7/223808672427',
   'description': '안녕하세요, <b>핀테크</b> 업계에 관심이 있는 여러분! 오늘은 <b>핀테크</b> 기업들이 고객 피드백을 효과적으로 활용하는 방안에 대해 이야기해보려고 합니다. 고객의 목소리를 경청하고 이를 반영하는 것은 기업의 성장과... ',
   'bloggername': '자신을 잃지 않기',
   'bloggerlink': 'blog.naver.com/mrlsa2333m7',
   'postdate': '20250401'},
  {'title': '<b>핀테크</b>와 전자 서명의 법적 효력',
   'link': 'https://blog.naver.com/pytv28ink2s/223812493187',
   'description': '오늘은 <b>핀테크</b> 산업의 발전과 더불어 중요성이 높아지고 있는 전자 서명의 법적 효력에 대해 이야기해보겠습니다. <b>핀테크</b>는 금융과 기술의 융합으로 많은 변화를 일으키고 있으며, 이러한 변화 속에서 전자... ',
   'bloggername': '행복한 나비의 비행',
   'bloggerlink': 'blog.naver.com/pytv28ink2s',
   'postdate': '20250401'},
  {'title': '<b>핀테크</b>의 글로벌 트렌드와 성장 가능성',
   'link': 'https://blog.naver.com/bvza2zhc53wch/223805904276',
   'description': '안녕하세요, <b>핀테크</b> 산업에 대한 관심이 날로 커지고 있는 요즘입니다. 오늘은 <b>핀테크</b>의 글로벌 트렌드와 그 성장 가능성에 대해 살펴보겠습니다. <b>핀테크</b>는 금융(Financial)과 기술(Technology)의 합성어로, 기술... ',
   'bloggername': '소중한 순간의 기록',
   'bloggerlink': 'blog.naver.com/bvza2zhc53wch',
   'postdate': '20250330'},
  {'title': '금융과 기술의 만남 - <b>핀테크</b>',
   'link': 'https://blog.naver.com/cjswowkrrk1130/223792409979',
   'description': '<b>핀테크</b>(Fintech)란? 금융(Finance)과 기술(Technology)을 합친 말로 금융관련 일을 기술로 더 쉽고 편하게... 복잡했던 금융거래가 이제는 손끝에서 해결되는 것을 <b>핀테크</b> 산업이라고 합니다. 예전에는 은행에 갈일을... ',
   'bloggername': '세컨 그라운드',
   'bloggerlink': 'blog.naver.com/cjswowkrrk1130',
   'postdate': '20250313'},
  {'title': '<b>핀테크</b>와 블록체인: 기술의 융합',
   'link': 'https://blog.naver.com/jpbiaoj5019m7/223807479451',
   'description': '있는 <b>핀테크</b>와 블록체인 기술의 융합에 대해 이야기해 보겠습니다. 이러한 두 가지 혁신 기술은 그 자체로도 강력하지만, 결합되어 새로운 가능성을 열어주고 있습니다. <b>핀테크</b>는 금융 서비스와 기술이 결합된... ',
   'bloggername': '꽃피는 봄날',
   'bloggerlink': 'blog.naver.com/jpbiaoj5019m7',
   'postdate': '20250330'},
  {'title': '<b>핀테크</b>로 쉽게 시작하는... 부동산 소액 가치 투자 (<b>핀테크</b> A to Z)',
   'link': 'https://blog.naver.com/realbuy_official/223631432229',
   'description': '안녕하세요 최근 스마트폰 하나로 은행 업무부터 투자까지 모든 금융 활동을 처리할 수 있는 시대가 되면서 ‘<b>핀테크</b>’(Fintech)’ 라는 용어를 한 번쯤 들어보셨을 텐데요! <b>핀테크</b>는 우리의 금융 생활을 더... ',
   'bloggername': '리얼바이 - 초대형 빌딩 투자의 시작',
   'bloggerlink': 'blog.naver.com/realbuy_official',
   'postdate': '20241024'},
  {'title': '전자금융공동망: <b>핀테크</b> 혁신의 기반, 과제와 미래 방향',
   'link': 'https://blog.naver.com/under13517/223815611094',
   'description': '전자금융공동망: <b>핀테크</b> 혁신의 기반, 과제와 미래 방향 전자금융공동망, 이름은 조금 딱딱하지만, 사실 우리가 매일 사용하는 간편결제나 송금 서비스 뒤에 숨어있는 <b>핀테크</b> 혁신의 숨은 공신이라고 할 수... ',
   'bloggername': '여행의디자인',
   'bloggerlink': 'blog.naver.com/under13517',
   'postdate': '20250331'},
  {'title': '<b>핀테크</b> 혁신: 편리함과 그림자, 균형 잡힌 금융 미래 모색',
   'link': 'https://blog.naver.com/regret13189/223816568553',
   'description': '<b>핀테크</b> 혁신: 편리함과 그림자, 균형 잡힌 금융 미래 모색 <b>핀테크</b>는 우리 삶을 정말 많이 바꿔놓았어. 스마트폰 하나로 은행 업무를 보고, 인공지능이 알아서 투자도 해준다니, 정말 놀라운 세상이지? 하지만... ',
   'bloggername': '경영 팁',
   'bloggerlink': 'blog.naver.com/regret13189',
   'postdate': '20250331'},
  {'title': '2024 코리아<b>핀테크</b>위크 / 쏘카 빌려 서울 야간 드라이브',
   'link': 'https://blog.naver.com/wogur003/223576113684',
   'description': '코리아<b>핀테크</b>위크 업무차 방문했다. 올해는 부스 참가를 따로 안 했지만 새 대표님이 A.I 맹신론자라는... <b>핀테크</b>위크 초창기에는 솔직히 다들 분위기상 억지로 참여하는, 뭔가 뜬 구름 잡는 느낌이었는데 A. I... ',
   'bloggername': '피리산적의 인생극장',
   'bloggerlink': 'blog.naver.com/wogur003',
   'postdate': '20240908'},
  {'title': '<b>핀테크</b> 혁신: 기회와 도전, 미래 금융의 균형 잡힌 시각',
   'link': 'https://blog.naver.com/literafatu11245/223816551377',
   'description': '<b>핀테크</b> 혁신: 기회와 도전, 미래 금융의 균형 잡힌 시각 <b>핀테크</b>, 다들 한 번쯤은 들어봤지? 금융과 기술이 만나서 우리 삶을 얼마나 편리하게 바꿔주는지! 정말 놀라운 변화가 아닐 수 없어. 모바일 결제부터... ',
   'bloggername': '리더십 노하우',
   'bloggerlink': 'blog.naver.com/literafatu11245',
   'postdate': '20250331'},
  {'title': '서울 <b>핀테크</b> 위크 2023 컨퍼런스 - 동대문 DDP',
   'link': 'https://blog.naver.com/joo1609/223232228599',
   'description': '서울 <b>핀테크</b> 위크 2023 동대문 ddp 아트홀 서울의 디지털금융 도시경쟁력을 높이고 <b>핀테크</b> 산업의 혁신과 발전을 위해 개최되는 서울 <b>핀테크</b> 위크 2023이 동대문 ddp 아트홀에서 개최된다고해서... ',
   'bloggername': '✨️뚜벅이주주 문화여행맛집 이야기',
   'bloggerlink': 'blog.naver.com/joo1609',
   'postdate': '20231009'},
  {'title': '지급준비자산제도와 <b>핀테크</b> 혁신의 상관관계',
   'link': 'https://blog.naver.com/jydyiagp2012j7/223806236554',
   'description': '오늘은 지급준비자산제도와 <b>핀테크</b> 혁신 간의 관계에 대해 깊이 있게 탐구해 보겠습니다. 디지털 금융이 발전함에 따라 기존 금융 시스템과 <b>핀테크</b> 기업 간의 경계가 점점 흐려지고 있으며, 이 과정에서... ',
   'bloggername': '소리 없는 음악',
   'bloggerlink': 'blog.naver.com/jydyiagp2012j7',
   'postdate': '20250330'},
  {'title': '<b>핀테크</b> 기업의 사회적 책임과 윤리',
   'link': 'https://blog.naver.com/cddrme203g4/223809740069',
   'description': '최근 <b>핀테크</b>(FinTech) 산업이 급속도로 성장함에 따라 이와 관련된 사회적 책임과 윤리에 대한 논의가 더욱 중요해지고 있습니다. <b>핀테크</b> 기업들은 혁신적인 금융 서비스와 기술을 통해 소비자들에게 편리함을... ',
   'bloggername': '꿈의 바람을 타고',
   'bloggerlink': 'blog.naver.com/cddrme203g4',
   'postdate': '20250331'},
  {'title': '<b>핀테크</b>로 진출하는 맨틀 네트워크(MNT)',
   'link': 'https://blog.naver.com/rusiper1000/223781111719',
   'description': '한국 <b>핀테크</b> 시장, 4년 뒤 84조로 성장 예상 한국경제 <b>핀테크</b>, 테크핀이라는 용어를 많이 들어보셨을텐데요. 국내 대표 <b>핀테크</b> 기업 토스의 창업자는 2024년에 한국의 <b>핀테크</b> 시장은 4년 뒤 84조로 성장할 것이라... ',
   'bloggername': '타락천사의 블로그',
   'bloggerlink': 'blog.naver.com/rusiper1000',
   'postdate': '20250303'},
  {'title': '김종서 ㈜아톤 대표 - ‘골리앗에 혁신을 더하다’, <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/monthlypeople/223787168709',
   'description': '금융권의 디지털 전환이 가속화되면서 <b>핀테크</b> 보안의 중요성이 더욱 커지고 있다. 특히 공인인증서... 이러한 변화의 흐름 속에서 ㈜아톤은 지난 25년간 금융권 <b>핀테크</b> 보안의 선두주자로서 혁신을... ',
   'bloggername': '월간인물 공식블로그',
   'bloggerlink': 'blog.naver.com/monthlypeople',
   'postdate': '20250307'},
  {'title': '[은생돋] <b>핀테크</b>에 죽고 사는 ‘탄력점포’ 딜레마',

# While True로 전체 데이터 가져오기

In [7]:
page = 1
start_num2 = 1
response_json3 = []
while True:
    url = "https://openapi.naver.com/v1/search/blog.json"
    Client_Id = "uk7phJIAYBDY5KptX5ev"
    Client_Secret = "cnGUx6svh_"
    payload = dict(query='핀테크', display=100, start=start_num2, sort="sim")
    headers = {"X-Naver-Client-Id" : Client_Id, 
               "X-Naver-Client-Secret" : Client_Secret}
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    response = r.json()
    total_pages = (response['total'] // 100) + 1
    response_json3.append(response)
    if start_num2 == 1000:
        break
    if start_num2 < 901: 
        start_num2 += 100
    elif start_num2 == 901:
        start_num2 += 99
    if page < total_pages:
        page += 1
    else:
        break
print(len(response_json3))

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
11

# 블로그, 책, 뉴스 동시에 수집하기

In [9]:
import time
response_json3 = []
for category in ['blog', 'news', 'book']:
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id = "uk7phJIAYBDY5KptX5ev"
        Client_Secret = "cnGUx6svh_"
        payload = dict(query='핀테크', display=100, start=start_num2, sort="sim")
        headers = {"X-Naver-Client-Id" : Client_Id, 
                   "X-Naver-Client-Secret" : Client_Secret}
        r = requests.get(url, params=payload, headers=headers)
        print(r.url)
        print(r.status_code)
        response = r.json()
        total_pages = (response['total'] // 100) + 1
        response_json3.append(response)
        if start_num2 == 1000:
            break
        if start_num2 < 901: 
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99
            
        if page < total_pages:
            page += 1
        else:
            break
        time.sleep(0.5)
    print(len(response_json3))

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
11
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200

KeyboardInterrupt:

# 블로그, 뉴스, 책 데이터 각각 저장하기

In [10]:
import time
keyword = input("검색할 키워드를 입력해 주세요")
response_blog = []
response_news = []
response_book = []
for category in ['blog', 'news', 'book']:
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id = "uk7phJIAYBDY5KptX5ev"
        Client_Secret = "cnGUx6svh_"
        payload = dict(query=keyword, display=100, start=start_num2, sort="sim")
        headers = {"X-Naver-Client-Id" : Client_Id, 
                   "X-Naver-Client-Secret" : Client_Secret}
        r = requests.get(url, params=payload, headers=headers)
        print(r.url, end="\r")
        print(r.status_code, end="\r")
        response = r.json()
        total_pages = (response['total'] // 100) + 1
        
        if category == 'blog':
            response_blog.append(response)
        elif category == 'news':
            response_news.append(response)
        elif category == 'book':
            response_book.append(response)
            
        if start_num2 == 1000:
            break
        if start_num2 < 901: 
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99
            
        if page < total_pages:
            page += 1
        else:
            break
        time.sleep(0.5)
print(len(response_blog))
print(len(response_news))
print(len(response_book))

검색할 키워드를 입력해 주세요인공지능
110ps://openapi.naver.com/v1/search/book.json?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&display=100&start=1000&sort=sim
11
11

In [11]:
def json_unpack(all_data):
    final_result = {}
    for page in all_data:
        for item in page['items']:
            for key, value in item.items():
                final_result.setdefault(key, []).append(value)

    df = pd.DataFrame(final_result)
    return df

In [13]:
import pandas as pd

In [14]:
for jsons, cat in zip([response_blog, response_news, response_book], ['blog', 'news', 'book']):
    unpack_result = json_unpack(jsons)
    unpack_result.to_csv(f"naver_{cat}_result.csv", encoding = 'utf-8', index=False)

# 3개 카테고리 수집 코드를 함수화하기

In [15]:
def naver_search(keyword, category):
    response_result = []
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id = "uk7phJIAYBDY5KptX5ev"
        Client_Secret = "cnGUx6svh_"
        payload = dict(query=keyword, display=100, start=start_num2, sort="sim")
        headers = {"X-Naver-Client-Id" : Client_Id, 
                   "X-Naver-Client-Secret" : Client_Secret}
        r = requests.get(url, params=payload, headers=headers)
        print(r.url, end="\r")
        print(r.status_code, end="\r")
        response = r.json()
        total_pages = (response['total'] // 100) + 1

        response_result.append(response)

        if start_num2 == 1000:
            break
        if start_num2 < 901: 
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99

        if page < total_pages:
            page += 1
        else:
            break
        time.sleep(0.2)

    return response_result

In [17]:
import time
keyword = input("검색할 키워드를 입력해 주세요")
for category in ['blog', 'news', 'book']:
    naver_search_result = naver_search(keyword, category)
    result_df = json_unpack(naver_search_result)
    display(result_df)
#     print(f"{category}_search_result: {len(naver_search_result)}")

검색할 키워드를 입력해 주세요인공지능

,title,link,description,bloggername,bloggerlink,postdate
0,학점은행제 <b>인공지능</b> 학위 취득 직장인도 할 수 있네요!,https://blog.naver.com/2_dl/223813189505,"등에 인공적으로 구현한, 모방한 기능을 갖춘 컴퓨터 시스템으로 이와 같이 지능을 만...",2_dl님의블로그,blog.naver.com/2_dl,20250328
1,<b>인공지능</b>학과 체계적인 대비방법,https://blog.naver.com/blackhole_chinese/22378...,<b>인공지능</b>학과 합격자의 후기를 소개합니다 <b>인공지능</b>학과 체계적...,묘한 교육 연구소,blog.naver.com/blackhole_chinese,20250306
2,<b>인공지능</b> 전문가 자격증 취득방법,https://blog.naver.com/mago41/223808447841,"<b>인공지능</b> 전문가 자격증 취득방법 최근 몇 년 사이, <b>인공지능</b...",정인춤터,blog.naver.com/mago41,20250324
3,<b>인공지능</b> 스피커 종류 KT 기가지니4 스펙 요금제 알아보기(lg...,https://blog.naver.com/minsha321/223816637896,"&quot; &quot; <b>인공지능</b> 스피커, 어떤 제품을 선택해야 좋을까...",일해라 절해라,blog.naver.com/minsha321,20250331
4,<b>인공지능</b>전문가 자격증 취득 과정 알아보고 연봉 정리,https://blog.naver.com/siren48/223808272439,속에서 <b>인공지능</b>은 빠질 수 없는 요소가 되어버렸습니다. 길을 찾을 때도...,Dan's Magic Castle,blog.naver.com/siren48,20250325
...,...,...,...,...,...,...
1095,안산시평생학습관 <b>인공지능</b>실무업무활용,https://blog.naver.com/eduansan/223760524551,2025 안산시평생학습관 피움과정 <b>인공지능</b>실무업무활용 <b>인공지능</...,안산시평생학습관,blog.naver.com/eduansan,20250214
1096,"딥러닝, PID 제어 대체 가능할까? <b>인공지능</b>의 도전",https://blog.naver.com/dean4001/223741995156,"PID 제어, <b>인공지능</b> 만나다 100년 가까이 산업 자동화와 공정 관리...",고양이집사 리샤's 포스트 IT,blog.naver.com/dean4001,20250130
1097,"<b>인공지능</b>팩토리, 디지털 혁신기업 글로벌 성장 R바우처...",https://blog.naver.com/venturesquare_/22368739...,(주)<b>인공지능</b>팩토리(대표 김태영)는 유성구청과 협력해 온프레미스 환경에...,VentureSquare,blog.naver.com/venturesquare_,20241209
1098,[내일배움카드] <b>인공지능</b> 교육 과정 국비지원 한국ICT인재개발원,https://blog.naver.com/pianogs/223552980735,안녕하세요 요즘 신문기사나 뉴스에 <b>인공지능</b>에 대해 자주 언급되어서 기사...,Just Moment,blog.naver.com/pianogs,20240819
1099,경기도민을 위한 <b>인공지능</b> 리터러시 교육 성황리에 종료,https://blog.naver.com/ysueroomy/223619817195,경기도 <b>인공지능</b> 리터러시 교육’이 10월 11일(금) 연성대학교 창의교...,"학생의 성장을 돕는 교육혁신의 중심, 연성대학교",blog.naver.com/ysueroomy,20241015

,title,originallink,link,description,pubDate
0,"&quot;앱 적용 <b>인공지능</b> 기술 총망라&quot; 배달의민족, '요즘...",https://www.newsis.com/view/NISX20250401_00031...,https://n.news.naver.com/mnews/article/003/001...,배달의민족(배민)을 운영하는 우아한형제들이 <b>인공지능</b>(AI) 중심 개발 ...,"Tue, 01 Apr 2025 09:26:00 +0900"
1,금목걸이 절도범 <b>인공지능</b> 선별 관제 시스템에 '딱 걸렸네',https://www.news1.kr/local/jeonbuk/5738541,https://n.news.naver.com/mnews/article/421/000...,중고 거래 앱 '당근마켓'을 통해 금목걸이를 건네받은 뒤 오토바이를 타고 도주한 4...,"Tue, 01 Apr 2025 11:23:00 +0900"
2,[단독] 학과명 '간판갈이'…유령 AI학과 넘친다,https://www.hankyung.com/article/2025033111641,https://n.news.naver.com/mnews/article/015/000...,국내 대학의 <b>인공지능</b>(AI) 관련 학과 규모가 학생 수 기준으로 5년간...,"Mon, 31 Mar 2025 17:54:00 +0900"
3,청소년 매체이용률 1위는 ‘숏폼’..절반은 생성형 <b>인공지능</b> 사용,http://www.fnnews.com/news/202504011129460011,https://n.news.naver.com/mnews/article/014/000...,또 청소년의 절반 정도가 생성형 <b>인공지능</b>(AI)을 사용하는 것으로 조사...,"Tue, 01 Apr 2025 12:01:00 +0900"
4,늘어나는 <b>인공지능</b> 음악…'AI 안 썼다' 보증해야 저작권 등록,https://www.yna.co.kr/view/AKR2025033115770000...,https://n.news.naver.com/mnews/article/001/001...,한음저협 '인간창작' 확인·보증 절차 추가…AI 사용 여부 실제 확인은 어려울 듯 ...,"Tue, 01 Apr 2025 07:00:00 +0900"
...,...,...,...,...,...
1095,유승민 &quot;그래서 엔비디아 같은 기업은 어떻게 만들 건가&quot;,https://www.newsis.com/view/NISX20250305_00030...,https://n.news.naver.com/mnews/article/003/001...,앞서 이 대표는 지난 2일 민주연구원 집단지성센터에 올라온 대담 영상에서 &quot...,"Wed, 05 Mar 2025 17:13:00 +0900"
1096,"수원시, 봄철 산불진화 모의훈련 실시",https://www.sentv.co.kr/article/view/sentv2025...,https://www.sentv.co.kr/article/view/sentv2025...,산불감시 드론 운용을 마친 뒤 상황판단 회의를 거쳐 훈련을 마무리했습니다. 시는 <...,"Fri, 14 Mar 2025 12:50:00 +0900"
1097,"한화생명, <b>인공지능</b> 컨택센터(AICC) 오픈",http://www.fins.co.kr/news/articleView.html?id...,http://www.fins.co.kr/news/articleView.html?id...,한화생명은 <b>인공지능</b> 컨택센터(AICC)를 오픈했다고 4일 밝혔다. AI...,"Tue, 04 Mar 2025 09:46:00 +0900"
1098,"IBK기업은행, 제3회 해군⸱해병대 <b>인공지능</b> 경진대회 후원",http://www.insidevina.com/news/articleView.htm...,http://www.insidevina.com/news/articleView.htm...,유일광 IBK기업은행 개인고객그룹 부행장(왼쪽)이 박노호 해군 정보화기획참모부장(준...,"Mon, 10 Mar 2025 15:58:00 +0900"
1099,"한화생명, <b>인공지능</b> 컨택센터 오픈",http://digitalchosun.dizzo.com/site/data/html_...,http://digitalchosun.dizzo.com/site/data/html_...,송정현 기자 | 한화생명이 ‘<b>인공지능</b> 컨택센터(AICC)’를 오픈했다고...,"Tue, 04 Mar 2025 10:12:00 +0900"

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"인공지능 (수학적 이해에서 알고리즘까지, 개정판)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_530905...,오상훈,26730,홍릉,20250311,9791156002635,
1,교실 밖 인공지능 수업 (우리의 상상을 미래의 현실로 만들어가는 인공지능의 세계를 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_337008...,김현정,12600,궁리,20220725,9788958207788,다가올 새로운 미래를 준비하는 청소년들을 위해 \nIT전문가가 현장에서 들려주는 생...
2,AI 리터러시 (인공지능 필수 지식부터 완벽 활용까지),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_516051...,김용성,22500,프리렉,20241202,9788965404026,AI 시대에 필수로 알아야 할 인공지능의 원리와 개념부터\n학생·직장인·공무원·교육...
3,된다! 하루 만에 끝내는 챗GPT 활용법 (인공지능에게 일 시키고 시간 버는 법),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_493627...,프롬프트 크리에이터,15480,이지스퍼블리싱,20240729,9791163036234,《된다! 하루 만에 끝내는 챗GPT 활용법》이 GPT-4o를 반영한 전면 개정 2판...
4,인공지능 시대의 컴퓨터 개론 (개정8판),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_365674...,김대수^김경동,25760,생능출판,20221227,9788970506173,"제1장에서는 디지털 혁명과 4차 산업혁명의 시대를 다루었다. 인공지능 기술, 디지털..."
...,...,...,...,...,...,...,...,...,...
1095,브리태니커 만화 백과 51: 인공지능,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324363...,봄봄 스토리,9900,미래엔아이세움,20170822,9788937888816,미국에서 인공지능을 연구하는 공 박사는 휴가를 맞아 쌍둥이 조카 슬기와 로운이의 집...
1096,4차 산업혁명과 인공지능 영어교육 (제2판),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324927...,김인석,22500,한국문화사,20210330,9791166850011,이 책은 영어교육을 담당하는 전문가들이 4차 산업혁명 시대 정신에 부합하는 영어교육...
1097,인공지능과 법률 서비스 분야의 혁신,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324776...,양종모,22500,한국학술정보,20210331,9791166033940,"인공지능의 개념과 개발 동향부터, 법률 서비스 영역에서의 인공지능 알고리즘 활용까지..."
1098,AI의 도전 (인공지능의 위협과 공존 그리고 기회),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324670...,현대원,18000,나남출판,20210410,9791197127984,"본격화한 인공지능의 도전, 어떻게 대응할 것인가?\n새로운 ‘초지능의 물결’과 인간..."
1099,인공지능 산업분야 주식투자 가이드,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324921...,비티타임즈 편집부,27000,비티타임즈,20210426,9791163452690,주식에 대한 책이 많이 있지만 챠트나 그래프등에 대한 분석 방법등 숲이 아닌 나무를...

In [1]:
import requests
url = "https://openapi.naver.com/v1/search/blog"
payload = {'query': '핀테크', 'display' : 100, 'start': 1, 'sort' : "sim"}
headers = {"X-Naver-Client-Id" :"uk7phJIAYBDY5KptX5ev", "X-Naver-Client-Secret" : "cnGUx6svh_"}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
data

https://openapi.naver.com/v1/search/blog?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200

{'lastBuildDate': 'Mon, 31 Mar 2025 17:23:42 +0900',
 'total': 456079,
 'start': 1,
 'display': 100,
 'items': [{'title': '<b>핀테크</b> 투자 후기',
   'link': 'https://blog.naver.com/kan1687/223812724931',
   'description': '<b>핀테크</b> 투자, 아직도 망설이고 계신가요?  여러분 혹시 이런 고민 해보신 적 있나요? &quot;<b>핀테크</b> 분야가 떴다는데, 지금 시작해도 괜찮을까? 좀 더 상황을 지켜봐야 하나?&quot; 사실 이런 생각은 투자를 고민하는 우리... ',
   'bloggername': '우정잉♥',
   'bloggerlink': 'blog.naver.com/kan1687',
   'postdate': '20250329'},
  {'title': '[<b>핀테크</b>] 2024년 <b>핀테크</b> 업계 결산: 놀라운 3가지 변화',
   'link': 'https://blog.naver.com/xoom777/223708685044',
   'description': '동안 <b>핀테크</b> 업계에는 예상치 못한 변화의 바람이 불었습니다. 한동안 주춤했던 트렌드가... 올 한 해 <b>핀테크</b> 업계를 뜨겁게 달군 3가지 트렌드에 대해 자세히 살펴보겠습니다. 암호화폐의 귀환, 기관... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241229'},
  {'title': '[인사이트 캠퍼스] 2025 동계 <b>핀테크</b> 캠프 (with 전주대학교... ',
   'link': 'https://blog.naver.com/fininsight/223734638126',
   'description': '전주대학교 친구들이 직접 여의도까지 방문하여 <b>핀테크</b>(FinTech)의 세계를 탐구할 기회를 가질 수... <b>핀테크</b>의 개념부터 해당 기술을 적용하는 사업 분야 그리고 앞으로의 트렌드까지 현업자의 시선에서 면밀하게... ',
   'bloggername': '핀인사이트 (Fininsight)',
   'bloggerlink': 'blog.naver.com/fininsight',
   'postdate': '20250122'},
  {'title': '[AI <b>핀테크</b>] AI와 빅데이터로 금융 시장을 재편하는 <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/jangpung_/223765345858',
   'description': '이제 대출도 AI가 하는 시대 출처 : 파가야 테크놀러지스 홈페이지 금융과 기술이 만나는 <b>핀테크</b>... 제공하는 <b>핀테크</b> 기업으로, 현재 미국, 이스라엘, 케이맨 제도 등여러나라에서 사업을 진행하고 있다.... ',
   'bloggername': '낭만을 꿈꾸는 일상',
   'bloggerlink': 'blog.naver.com/jangpung_',
   'postdate': '20250218'},
  {'title': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대',
   'link': 'https://blog.naver.com/jaso_/223736810791',
   'description': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대 IPAY ETF는 모바일 결제 산업에 투자하는 ETF로 <b>핀테크</b>관련주라고 보시면 되는데요. 이번 포스팅에선 IPAY <b>핀테크</b>관련주 ETF, 투자수익률, 미국 CBDC... ',
   'bloggername': '미국주식 퍼주마',
   'bloggerlink': 'blog.naver.com/jaso_',
   'postdate': '20250130'},
  {'title': '맨틀 MNT 코인 디파이 <b>핀테크</b> 서비스 소개',
   'link': 'https://blog.naver.com/tmglove/223781181469',
   'description': '웹2와 웹3을 아우르며 기관과 개인 그리고 리테일을 위한 다양한 <b>핀테크</b> 서비스 출시를 준비하고 있다고 하는데요. 그래서 오늘은 MNT 코인의 디파이 <b>핀테크</b> 서비스에 대해 알아보겠습니다. <b>핀테크</b>로... ',
   'bloggername': 'Hello-',
   'bloggerlink': 'blog.naver.com/tmglove',
   'postdate': '20250302'},
  {'title': '[<b>핀테크</b> 리더] # 2024 금융위원회 선정 10대 기업 _ 1편',
   'link': 'https://blog.naver.com/koreafintech/223675560515',
   'description': "[<b>핀테크</b> 리더] ⭐ # 2024 금융위원회 선정 10대 기업 _ 1편 금융위원회는 &lt;코리아 <b>핀테크</b> 위크 2024&gt;에서 작년에 이어 'K-Fintech 30' 프로젝트에 선정된 유망 <b>핀테크</b> 기업 10개사를 발굴하여 소개하였습니다. 'K... ",
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241128'},
  {'title': '맨틀 네트워크 코인 MNT <b>핀테크</b> 서비스 등장',
   'link': 'https://blog.naver.com/ghfjvb465/223781841217',
   'description': '맨틀네트워크 코인 <b>핀테크</b>와 크립토 경계 허물기 소개, 시세, 전망 코하! 경제적 자유 얻기... 이번 포스팅에서는 맨틀네트워크 코인 MNT의 <b>핀테크</b> 분야 진출 서비스 소개에 대한 내용을 함께 알아보는... ',
   'bloggername': '노마드신지테의 경제적자유얻기 챌린지',
   'bloggerlink': 'blog.naver.com/ghfjvb465',
   'postdate': '20250303'},
  {'title': '신규 상장 더즌 <b>핀테크</b> B2B 기업용 금융통신망 쉿 쉿 조용 조용',
   'link': 'https://blog.naver.com/2yongki/223805949459',
   'description': '기업 개요 20017년 설립 기업용 금융 통신망 서비스를 제공하는 <b>핀테크</b> 업체 금융 인프라를 기반으로... ② 경쟁 심화: * <b>핀테크</b> 시장은 경쟁이 치열하며, 새로운 경쟁자의 등장 가능성도 있습니다. * 새로운... ',
   'bloggername': '행복한남 경제야놀자',
   'bloggerlink': 'blog.naver.com/2yongki',
   'postdate': '20250323'},
  {'title': '테크놀로지스(PGY): AI 기반 대출 혁신의 주목받는 <b>핀테크</b> 기업',
   'link': 'https://blog.naver.com/an5217/223810108719',
   'description': '최근 <b>핀테크</b> 업계에서 주목받는 기업 **파가야 테크놀로지스(NASDAQ:PGY)**가 투자자와 애널리스트들... 제공하는 <b>핀테크</b> 기업입니다. 머신러닝 알고리즘을 통해 개인 대출, 자동차 대출, POS(Point-of-Sale)... ',
   'bloggername': '오늘 하루도 절도있고 검소하게',
   'bloggerlink': 'blog.naver.com/an5217',
   'postdate': '20250326'},
  {'title': '맨틀 코인 전망 디파이를 넘어 <b>핀테크</b>로 확장하는 미래',
   'link': 'https://blog.naver.com/duswnswlstlf/223782041308',
   'description': 'WEB2와 WEB3를 아우르는 기업들이 늘어나고 있지만 현실은 <b>핀테크</b> 기업들이 크립토 산업에 진출할 뿐, 크립토 기업들이 <b>핀테크</b> 사업으로 진출한 경우는 없네요. 가끔은 왜 WEB3 기업들은 디파이를 넘어서 WEB2의... ',
   'bloggername': '이기사 블로그',
   'bloggerlink': 'blog.naver.com/duswnswlstlf',
   'postdate': '20250303'},
  {'title': '서울형 R&amp;D <b>핀테크</b> 기술사업화 지원사업 완벽 가이드!',
   'link': 'https://blog.naver.com/thebsc777/223802246310',
   'description': '이번에 서울경제진흥원에서 공고한 25년 서울형 R&amp;D <b>핀테크</b> 기술사업화 지원사업 에 대해 상세히 알아보겠습니다. <b>핀테크</b> 분야 기업이라면 절대 놓치면 안 될 이번 지원사업, 꼼꼼히 살펴볼게요! 1. 지원... ',
   'bloggername': '정책지원알림',
   'bloggerlink': 'blog.naver.com/thebsc777',
   'postdate': '20250323'},
  {'title': '네이버클라우드 X 서울대학교 KDT 빅데이터 <b>핀테크</b> 전문가 과정',
   'link': 'https://blog.naver.com/n_cloudplatform/223790788385',
   'description': '서울대학교 KDT 빅데이터 <b>핀테크</b> 전문가 과정에 캡스톤 참여기업으로 함께한 네이버클라우드의... 서울대학교 빅데이터 <b>핀테크</b> AI 고급 전문가 과정 서울대학교가 주관하는 고용노동부의 K... ',
   'bloggername': '네이버클라우드 (NAVER Cloud)',
   'bloggerlink': 'blog.naver.com/n_cloudplatform',
   'postdate': '20250311'},
  {'title': '25년 금융 클라우드 지원사업 <b>핀테크</b> 기업 클라우드는... ',
   'link': 'https://blog.naver.com/xeno_solution/223791865385',
   'description': '이번에 <b>핀테크</b> 기업 담당하고 계신 분들이 주목할 만한 소식이 업데이트되어 가지고 왔습니다~ 다름... <b>핀테크</b> 기업의 경우 보안 기능과 빠르게 처리가 가능한 인프라를 요구할 수밖에 없습니다. 그렇기... ',
   'bloggername': '클라우드를 가장 잘 하는 회사, 제노솔루션',
   'bloggerlink': 'blog.naver.com/xeno_solution',
   'postdate': '20250311'},
  {'title': '페이버스와 알아보는 2025 글로벌 <b>핀테크</b> 규제 변화',
   'link': 'https://blog.naver.com/payverse/223809522693',
   'description': '2025년 주목해야 할 글로벌 <b>핀테크</b> 규제 변화 안녕하세요, 페이버스 입니다 :) <b>핀테크</b> 산업은 전 세계적으로 빠르게 성장하고 있으며, 이에 따라 각국의 규제 환경도 계속해서 변화하고 있습니다.... ',
   'bloggername': '페이버스(PayVerse)',
   'bloggerlink': 'blog.naver.com/payverse',
   'postdate': '20250326'},
  {'title': '<b>핀테크</b> 개인 경제에 혁명적 영향을 느끼게 하다',
   'link': 'https://blog.naver.com/anawoncham/223685650464',
   'description': '<b>핀테크</b> FinTech는 Finance과 Technology의 결합으로, 최근 몇 년간 급속도로 발전하고 있는 분야예요. 이제는 우리 생활의 많은 부분에서 <b>핀테크</b>는 개인 경제에 혁명인 영향을 느끼게 하고 있는데요. 오늘은... ',
   'bloggername': '♣ 끄적이내 ♣',
   'bloggerlink': 'blog.naver.com/anawoncham',
   'postdate': '20241207'},
  {'title': '2025년 <b>핀테크</b> 트렌드: 새로운 금융 패러다임과 기회의 장',
   'link': 'https://blog.naver.com/dismalist/223762273788',
   'description': '2025년, <b>핀테크</b>(FinTech)는 더 이상 &quot;미래의 금융&quot;이 아닙니다. 바로 우리의 일상에 깊숙이 스며든 현실이자 새로운 금융 패러다임을 형성하는 강력한 동력인데요. 이번 포스팅에서는 2025년 <b>핀테크</b> 산업을... ',
   'bloggername': '마법고양이의 기묘한 이야기',
   'bloggerlink': 'blog.naver.com/dismalist',
   'postdate': '20250216'},
  {'title': '“<b>핀테크</b>-금융회사-투자기관 만남의 장” ｢제2회 <b>핀테크</b> 오픈... ',
   'link': 'https://blog.naver.com/blogfsc/223666157308',
   'description': '-<b>핀테크</b>-금융회사 협업 및 <b>핀테크</b> 기업 투자 유치를 확대하는 교류 행사 -금융위원회, <b>핀테크</b> 산업의 지속 성장을 위해 과감한 디지털 금융정책 추진 금융위원회는 11월 19일(화), 서울 창업허브(공덕)에서... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20241119'},
  {'title': '<b>핀테크</b> 전문가 국비지원 과정 - KG 이니시스 실무자 멘토링',
   'link': 'https://blog.naver.com/gkea04/223815900160',
   'description': '<b>핀테크</b> 산업의 현황과 전망 <b>핀테크</b>(FinTech)는 금융(Finance)과 기술(Technology)의 합성어로, IT 기술을 활용하여 금융 서비스를 제공하는 산업을 말합니다. 최근 몇 년간 <b>핀테크</b> 산업은 빠르게 성장하고 있으며, 이는... ',
   'bloggername': 'KG 에듀원 교육 상담님의 블로그',
   'bloggerlink': 'blog.naver.com/gkea04',
   'postdate': '20250331'},
  {'title': '[기자단 뉴스] 보험 <b>핀테크</b> 트렌드 (인슈어테크/온디맨드 보험)',
   'link': 'https://blog.naver.com/koreafintech/223661661653',
   'description': '보험 <b>핀테크</b> 트렌드 제12기 대학생 기자단 이서현 인슈어테크 인슈어테크는 보험과 기술의 합성어로... 보험 <b>핀테크</b> 트렌드 인슈어테크와 온디맨드 보험은 보험 산업의 혁신을 이끄는 핵심 요소로, 소비자에게... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241118'},
  {'title': '<b>핀테크</b>로 외국에 보내는 송금 비용 낮추기',
   'link': 'https://blog.naver.com/e9pay7200/223790123142',
   'description': '그중에서도 스마트폰을 이용해 금융업무를 볼 수 있게 해주는 <b>핀테크</b> 기술의 등장으로 금융시장에서 상당한 변화를 맞이하게 됐답니다. <b>핀테크</b>의 등장으로 현재 대부분의 금융업무는 스마트폰을 통해... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9pay7200',
   'postdate': '20250310'},
  {'title': '<b>핀테크</b> 뜻 종류 기업 국내 미국 관련주 총정리!',
   'link': 'https://blog.naver.com/se4125/223711366625',
   'description': '<b>핀테크</b>는 금융과 기술의 결합으로, 우리의 금융 생활을 혁신하는 핵심 분야로 떠오르고 있습니다. 간편결제, 대출, 투자, 자산관리가지 <b>핀테크</b>는 더 이상 선택이 아닌 필수가 되고 있는데요. 그런데... ',
   'bloggername': '자유연구소',
   'bloggerlink': 'blog.naver.com/se4125',
   'postdate': '20250101'},
  {'title': '[4/14까지][서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고... ',
   'link': 'https://blog.naver.com/ilsinbc/223800254706',
   'description': '기술 [서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고(서울형 R&amp;D 지원사업) 소관부처·지자체 : 서울특별시 사업수행기관 : 서울경제진흥원 신청기간 : 2025.03.25 ~ 2025.04.14 사업개요 2025년 <b>핀테크</b>... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250318'},
  {'title': '<b>핀테크</b> 뜻 투자방법 알아봐요',
   'link': 'https://blog.naver.com/jungmk1570/223602309573',
   'description': '오늘은 <b>핀테크</b>(FinTech)를 활용한 소액 투자에 대해 이야기해보려고 해요. 최근 주식시장과 금리인하의 변동성으로 인해 많은 사람들이 안정적인 투자처를 찾고 있습니다. 이러한 상황에서 <b>핀테크</b> 플랫폼을... ',
   'bloggername': '재테크 허니',
   'bloggerlink': 'blog.naver.com/jungmk1570',
   'postdate': '20241001'},
  {'title': '테솔 컬리지, 2025년 <b>핀테크</b>허브 기업 선정!',
   'link': 'https://blog.naver.com/tesol_college/223813299337',
   'description': '2025년 <b>핀테크</b>허브입주기업으로 선정되었습니다! 이번 선정을 통해 테솔컬리지는 영어교육과 기술이 융합된 에듀테크 기반 사업모델을 더욱 본격적으로 전개할 수 있게 되었습니다.  <b>핀테크</b>허브란?... ',
   'bloggername': '테솔 자격증 : TESOL College',
   'bloggerlink': 'blog.naver.com/tesol_college',
   'postdate': '20250328'},
  {'title': '<b>핀테크</b> 기업을 위한 금융 클라우드 지원 사업 (~4/4)',
   'link': 'https://blog.naver.com/n_cloudplatform/223790696137',
   'description': '돈과 개인정보를 다루는 만큼 금융∙<b>핀테크</b> 업계는 보안이 정말 중요한데요. 그렇기 때문에 금융∙<b>핀테크</b> 기업이 혁신적인 서비스를 개발하기 위해선 믿을 수 있는 안전한 클라우드 환경이 꼭... ',
   'bloggername': '네이버클라우드 (NAVER Cloud)',
   'bloggerlink': 'blog.naver.com/n_cloudplatform',
   'postdate': '20250310'},
  {'title': '<b>핀테크</b>로 바뀐 금융의 미래... 2025 일본 <b>핀테크</b> 혁신기업 연수단',
   'link': 'https://blog.naver.com/iloveimier/223768487894',
   'description': '바로 <b>핀테크</b>(FinTech)의 등장 덕분인데요!! 오늘은 우리 생활 속 중요한 부분으로 자리 잡은 <b>핀테크</b>에 대해 좀 더 깊이 알아보고, 이와 관련된 연수 프로그램을 소개해 드리겠습니다! <b>핀테크</b>란? <b>핀테크</b>는... ',
   'bloggername': '한경협국제경영원(IMI) 블로그',
   'bloggerlink': 'blog.naver.com/iloveimier',
   'postdate': '20250221'},
  {'title': '대한민국의 디지털 금융 혁신: 세계가 주목하는 K-<b>핀테크</b>',
   'link': 'https://blog.naver.com/tnalsrla2002/223797958470',
   'description': '대한민국은 최첨단 디지털 금융 기술을 기반으로 <b>핀테크</b>(FinTech) 강국으로 성장하고 있으며, 글로벌... 글로벌 <b>핀테크</b> 시장을 선도하는 대한민국 한국의 <b>핀테크</b> 기업들은 글로벌 시장에 진출하며, 해외에서도... ',
   'bloggername': 'IT감사팀장이 전하는 보안•감사•포렌식',
   'bloggerlink': 'blog.naver.com/tnalsrla2002',
   'postdate': '20250316'},
  {'title': '[ 업스타트 홀딩스 ] AI와 금융의 만남,<b>핀테크</b> 대출 시장을... ',
   'link': 'https://blog.naver.com/gopagi7/223814284723',
   'description': '개요 업스타트 홀딩스(티커: UPST)는 AI 기반 대출 플랫폼을 운영하는 <b>핀테크</b> 기업으로, 전통적인... ㆍ규제 및 경쟁 심화 → <b>핀테크</b> 기업 및 전통 금융기관과 경쟁. 5. 향후 전망 ㆍAI 모델 고도화 → 신용... ',
   'bloggername': '사고싶은주식',
   'bloggerlink': 'blog.naver.com/gopagi7',
   'postdate': '20250329'},
  {'title': '[<b>핀테크</b>] 2025 <b>핀테크</b> 전망: 주목해야 할 10가지 변화',
   'link': 'https://blog.naver.com/xoom777/223702449504',
   'description': '2025년이 다가오면서, 금융 기술, 즉 <b>핀테크</b> 분야에서 흥미로운 변화들이 예상되고 있어. 인공지능의... 이제 2025년에 주목해야 할 10가지 <b>핀테크</b> 트렌드를 함께 살펴보자. 1. 웰스테크(WealthTech)의 부상... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241223'},
  {'title': '소셜 <b>핀테크</b>, 왜 사람들이 계속 이용할까?',
   'link': 'https://blog.naver.com/flyfirst0101/223789749173',
   'description': '<b>핀테크</b>를 활용해서 2~3천만원의 결혼 자금을 만드는 사람부터 1천만원 이내의 시드머니를 빠른 시간내에 확보하여 투자에 활용하는 사람까지 참여자들이 급속도로 늘어나고 있습니다. 재밌는 점은 소셜 <b>핀테크</b>... ',
   'bloggername': '아임인 공식 블로그',
   'bloggerlink': 'blog.naver.com/flyfirst0101',
   'postdate': '20250309'},
  {'title': '[기자단 뉴스] 2024년 <b>핀테크</b> 해외 이슈',
   'link': 'https://blog.naver.com/koreafintech/223621158409',
   'description': '2024년 <b>핀테크</b> 해외 이슈 제12기 대학생 기자단 이서현 이제는 손바닥 결제 시대? 중국의 텐센트가... 기사를 작성하며 제가 ‘손바닥 결제’와 ‘암호화폐 채굴’이라는 주제를 선택한 이유는 <b>핀테크</b> 분야의... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241016'},
  {'title': '아프리카 스타트업 생태계의 <b>핀테크</b> 중심 현상 속 주요... ',
   'link': 'https://blog.naver.com/viewist/223662800063',
   'description': "최근 한 자리에서 아프리카 스타트업 생태계의 주요 특징 중 하나가 '<b>핀테크</b> 중심의 성장'이라고... 아프리카 스타트업 생태계는 <b>핀테크</b> 중심지? 가장 최근 유니콘 기업으로 등극한 나이지리아의 모니포인트를... ",
   'bloggername': '아프리카의 IT와 스타트업 <<AFRITUP 아프릿업>>',
   'bloggerlink': 'blog.naver.com/viewist',
   'postdate': '20241116'},
  {'title': '[프로모션] 최대 9600만원 지원, NHN Cloud <b>핀테크</b> 기업 수요... ',
   'link': 'https://blog.naver.com/nhncloud_official/223805041831',
   'description': 'NHN Cloud는 <b>핀테크</b> 기업에게 중요한 안전한 인프라와 폭넓은 기술 지원을 5년 연속 제공하고 있습니다. NHN Cloud의 <b>핀테크</b> 기업을 위한 특별한 혜택을 안내해 드립니다. ‘금융 클라우드 지원사업’이란?... ',
   'bloggername': '유연하게 안전하게 비즈니스에 힘이 되다 ☁️',
   'bloggerlink': 'blog.naver.com/nhncloud_official',
   'postdate': '20250325'},
  {'title': '<b>핀테크</b> 개발자가 되기 위해 필요한 역량과 취업 준비 방법',
   'link': 'https://blog.naver.com/alsldd3/223812739187',
   'description': '<b>핀테크</b> 개발자가 되기 위해 필요한 역량과 취업 준비 방법 안녕하세요. 적어보았다입니다. 최근 금융과 기술이 융합된 <b>핀테크</b> 산업이 빠르게 성장하면서, <b>핀테크</b> 개발자에 대한 수요도 증가하고 있는데요.... ',
   'bloggername': '✍적어보았다.✍',
   'bloggerlink': 'blog.naver.com/alsldd3',
   'postdate': '20250328'},
  {'title': '<b>핀테크</b> 뜻 관련주 기업 추천앱 예시 알아보기',
   'link': 'https://blog.naver.com/choi9503/223713796013',
   'description': '<b>핀테크</b> 뜻 관련주 기업 추천앱 예시 알아보기 최근 몇 년간 <b>핀테크</b>라는 산업의 성장이 눈에 띄게 증가하고 있습니다 특히 아세안 지역에서의 확장이 두드러지고 있는데, 인도네시아나 말레이시아 그리고... ',
   'bloggername': '부동산 경제 건강 일상 맛집 이야기 !!',
   'bloggerlink': 'blog.naver.com/choi9503',
   'postdate': '20250104'},
  {'title': '<b>핀테크</b> 기업 종류 뜻 및 서비스와 관련 용어',
   'link': 'https://blog.naver.com/possiblehoya/223387198263',
   'description': '이번 포스팅에서는 우리나라에서 카카오페이, 네이버페이 등으로 유명한 <b>핀테크</b> 기업 종류와 뜻 그리고 관련 서비스와 용어 등에 대해 정리해 보도록 하겠습니다! <b>핀테크</b> 뜻 무엇일까?! <b>핀테크</b>(FinTech)는... ',
   'bloggername': '커피 이코노미스트',
   'bloggerlink': 'blog.naver.com/possiblehoya',
   'postdate': '20240318'},
  {'title': '<b>핀테크</b> 뜻 유래 기업 사례',
   'link': 'https://blog.naver.com/toresi/223471507785',
   'description': '<b>핀테크</b> 하루 1분 금융경제용어 안녕하세요. ^^ 오늘의 경제용어입니다. <b>핀테크</b> 뜻은 무엇인가? <b>핀테크</b>(FinTech) 금융(Finance)과 기술(Technology)의 합성어로, 금융 서비스를 기술적으로 혁신하여 융합하는 것을... ',
   'bloggername': '은행원쀼에게 금융 묻고 더블로',
   'bloggerlink': 'blog.naver.com/toresi',
   'postdate': '20240607'},
  {'title': '서울<b>핀테크</b>랩, ‘<b>핀테크</b> 스타트업을 위한 정부지원사업·R&amp;D... ',
   'link': 'https://blog.naver.com/venturesquare_/223727540072',
   'description': '서울<b>핀테크</b>랩은 1월 14일 서울<b>핀테크</b>랩에서 <b>핀테크</b> 기업을 대상으로 ‘2025년 서울<b>핀테크</b>랩과 함께하는 <b>핀테크</b> 스타트업을 위한 정부지원사업·R&amp;D·TIPS 알아보기’ 컨퍼런스를 개최하고 마무리했다고 밝혔다.... ',
   'bloggername': 'VentureSquare',
   'bloggerlink': 'blog.naver.com/venturesquare_',
   'postdate': '20250116'},
  {'title': '[3/26까지][금융위원회]2025년 제1차 <b>핀테크</b> 해외진출 컨설팅... ',
   'link': 'https://blog.naver.com/ilsinbc/223788341613',
   'description': '수출 2025년 제1차 <b>핀테크</b> 해외진출 컨설팅 참여기업 모집 공고 소관부처·지자체 : 금융위원회 사업수행기관 : 한국<b>핀테크</b>지원센터 신청기간 : 2025.03.05 ~ 2025.03.26 사업개요 한국<b>핀테크</b>지원센터(이하... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250308'},
  {'title': '더즌 공모주 수요예측 결과 <b>핀테크</b> 관련주',
   'link': 'https://blog.naver.com/bss2062/223792343321',
   'description': '더즌 공모주 수요예측 결과 <b>핀테크</b> 관련주 카카오페이의 자회사로도 알려져 있는 더즌이 내일 청약에... 기업정보 더즌은 인터넷, 모바일을 통해 간편하게 금융 거래를 제공해 주는 <b>핀테크</b> 기업이다. 우리가... ',
   'bloggername': '슈레카의 경제노트',
   'bloggerlink': 'blog.naver.com/bss2062',
   'postdate': '20250311'},
  {'title': 'K-<b>핀테크</b> 글로벌화를 통한 성장(Scale-up) 지원',
   'link': 'https://blog.naver.com/blogfsc/223749886170',
   'description': '2025년 제1차 「<b>핀테크</b> 지원협의체」 개최 -해외진출 지원 프로그램 예산 신설 등 정부·금융회사 연계 해외진출 지원 -코리아 <b>핀테크</b> 위크(AI와 <b>핀테크</b>를 주제로 11월 개최) 글로벌존 확장 예정... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250206'},
  {'title': '글로벌 금융 혁신을 향한 도전 : 쿠콘, 싱가폴 <b>핀테크</b> 페스티벌... ',
   'link': 'https://blog.naver.com/webcashgroup/223660359266',
   'description': 'WE-하 오늘 전해 드릴 이야기는 최근 비즈니스 데이터 플랫폼 기업 쿠콘이 세계 최대 <b>핀테크</b> 행사인 ‘싱가포르 <b>핀테크</b> 페스티벌 2024’에 참가했다는 소식입니다! 싱가포르 <b>핀테크</b> 페스티벌은 매년 전 세계의... ',
   'bloggername': '웹케시그룹 공식 블로그',
   'bloggerlink': 'blog.naver.com/webcashgroup',
   'postdate': '20241114'},
  {'title': '이것도 <b>핀테크</b>? 운전 습관에 따라 보험료가... ',
   'link': 'https://blog.naver.com/koreafintech/223803803517',
   'description': '이것도 <b>핀테크</b>? #1편 운전 습관에 따라 보험료가 달라지는 BBI (Behavior-Based Insurance) 인슈어테크로... 오늘은 보험의 <b>핀테크</b>인 인슈어테크(InsureTech) 중 “운전행태 기반 자동차 보험 (BBI, Behavior-Based Insurance)... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250321'},
  {'title': 'AI <b>핀테크</b>와 재테크',
   'link': 'https://blog.naver.com/commbooks/223704297144',
   'description': 'AI와 <b>핀테크</b> 기술이 금융과 재테크 분야를 어떻게 혁신하는지 탐구한다. AI 기반 로보어드바이저와... AI와 <b>핀테크</b> 기술을 효과적으로 활용한 재테크 전략과 함께 윤리적 기준을 고려한 금융 서비스의 미래를... ',
   'bloggername': '커뮤니케이션북스',
   'bloggerlink': 'blog.naver.com/commbooks',
   'postdate': '20241224'},
  {'title': '경제용어 <b>핀테크</b>,(모바일 시대)',
   'link': 'https://blog.naver.com/expert_1/223784395284',
   'description': '<b>핀테크</b>가 무엇인지 그 개념과 어떠한 분야에서 유용하게 쓰이고 있는지 간단하게 정리를 해보겠습니다. <b>핀테크</b>(FinTech/ Financial Technology)는 금융(Finance)과 기술(Technology)이 합쳐진 말입니다. 금융 서비스와... ',
   'bloggername': '빛을 담는 마법사',
   'bloggerlink': 'blog.naver.com/expert_1',
   'postdate': '20250305'},
  {'title': "'<b>핀테크</b>'에 대해서 알고있나요?",
   'link': 'https://blog.naver.com/mmdm1989/223669850292',
   'description': "'<b>핀테크</b>'란 금융(Finance)과 기술(Technology)의 합성어로 금융과 정보통신(IT)기술의 융합을 통한... <b>핀테크</b>는 2000년대 초반, 인터넷이 발달하면서 태동하였습니다. 직접적으로 영향을 미친 것은... ",
   'bloggername': 'SD명문학원',
   'bloggerlink': 'blog.naver.com/mmdm1989',
   'postdate': '20241122'},
  {'title': '금융의 디지털 혁신을 만들어준 <b>핀테크</b>',
   'link': 'https://blog.naver.com/kiat_tech/223691416200',
   'description': '<b>핀테크</b> 2.0 시대 돌입 ✔ <b>핀테크</b>는 스마트폰 등장 이후 디지털 결제, 대출, 투자 등으로 확장된 금융 혁신 기술 ✔ AI 기반 <b>핀테크</b>는 개인화된 금융 비서 역할과 효율성 극대화로 스마트한 금융 서비스 제공... ',
   'bloggername': '한국산업기술진흥원 블로그',
   'bloggerlink': 'blog.naver.com/kiat_tech',
   'postdate': '20241227'},
  {'title': '금융산업 전문인력 양성 ‘<b>핀테크</b> 캠프’ 운영',
   'link': 'https://blog.naver.com/leebangheui/223724159445',
   'description': '전주대학교(총장 박진배) 대학일자리플러스센터는 <b>핀테크</b> 산업에 관심이 있는 재학생 및 졸업생 29명을 대상으로 지난 1월 7일부터 3박 4일 간 서울국제금융센터(One IFC)에서“<b>핀테크</b> 캠프”를 운영했다고... ',
   'bloggername': 'BANGABANGA',
   'bloggerlink': 'blog.naver.com/leebangheui',
   'postdate': '20250113'},
  {'title': '미국과 영국 <b>핀테크</b>(Fintech)석사 추천학교 (feat.... ',
   'link': 'https://blog.naver.com/mskonan/223652313232',
   'description': '요즘 <b>핀테크</b>(Fintech)에 대한 관심이 높아지고 있습니다. 오늘은 미국과 영국에서 <b>핀테크</b>(Fintech)를 공부할수 있는 학교를 살펴보겠습니다. <b>핀테크</b>(Fintech)란 금융(Financial)과 기술... ',
   'bloggername': '30년 유학전문가의 유학이야기',
   'bloggerlink': 'blog.naver.com/mskonan',
   'postdate': '20241108'},
  {'title': '2025년! 한국 <b>핀테크</b>의 기업공개(IPO)가 시작된다.',
   'link': 'https://blog.naver.com/sijifs/223710220973',
   'description': '한국 <b>핀테크</b>의 기업공개(IPO)가 시작된다. 한국 <b>핀테크</b> 기업, 10년만에 흑자 전환 날짜 2024.12.31. 신문사 한국경제 기사제목 &quot;10여년 만의 흑자&quot;…<b>핀테크</b>社 내년 대도약하나 What <b>핀테크</b> 토스 앱을 운영하고... ',
   'bloggername': '[MitakuyeOyasin] 사진-책-연극-뮤지컬-동물-스페인',
   'bloggerlink': 'blog.naver.com/sijifs',
   'postdate': '20241231'},
  {'title': '[예산소진시까지][금융위원회]2025년 <b>핀테크</b> 보안지원 사업 공고',
   'link': 'https://blog.naver.com/ilsinbc/223773767425',
   'description': '기술 2025년 <b>핀테크</b> 보안지원 사업 공고 소관부처·지자체 : 금융위원회 사업수행기관 : 한국<b>핀테크</b>지원센터 신청기간 : 예산 소진시까지 사업개요 오픈뱅킹 참여기업, 금융규제 테스트베드 선정기업... ',
   'bloggername': '경영지도사 김진영의 105세 경영',

In [2]:
payload

{'query': '핀테크', 'display': 100, 'start': 1, 'sort': 'sim'}

In [3]:
headers

{'X-Naver-Client-Id': 'uk7phJIAYBDY5KptX5ev',
 'X-Naver-Client-Secret': 'cnGUx6svh_'}

네이버 검색 API를 이용해서 책을 검색하고 결과를 데이터프레임으로 만드세요.
* 검색어는 input()을 이용해서 입력받은 값을 이용하세요.

In [4]:
import requests
import pandas as pd

In [5]:
def json_unpack(data):
    result = {}
    for item in data['items']:
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    df = pd.DataFrame(result)
    return df

In [6]:
keyword = input("검색할 키워드를 입력해 주세요: ")

검색할 키워드를 입력해 주세요: 파이썬

In [7]:
url = "https://openapi.naver.com/v1/search/book.json"
Client_Id = "uk7phJIAYBDY5KptX5ev"
Client_Secret = "cnGUx6svh_"
headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
payload = dict(query=keyword, display=100, start=1000, sort="sim")
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
print("전체 검색 데이터 수: ", data['total'], "검색할 페이지 수:", (int(data['total'])//100)+1)
result_df = json_unpack(data)
result_df

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324920...,김문권,0,위키북스,20180529,9791158391065,강화학습은 스스로 학습하는 머신러닝 기법으로서 주식 데이터 학습에 잘 적용되는 기법...
1,슬기로운 코딩 생활 with 파이썬 으랏차차 기초편 (즐겁게 시작하고 똑똑하게 끝내...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324902...,김정욱,0,루비페이퍼,20180515,9791186710333,"수학, 과학, 국어, 사회 등 실제 초중등 교과 과목과 연계된 예제로 코딩력과 학습..."
2,2024 내일은 빅데이터분석기사 실기 with 파이썬 (제6회부터 변경된 작업형 제...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_434140...,Jade Jeong,20700,김앤북,20231030,9788965127925,「2024 내일은 빅데이터분석기사 실기」는 자격증을 준비하는 수험생 & 재직자(비전...
3,2024 빅데이터분석기사 실기 한권완성: 파이썬(Python) (작업형 제3유형 완...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_461080...,최예신^박진원^이경숙^김주현,27000,예문에듀,20240520,9791163862833,빅데이터분석기사 실기시험 초단기 합격을 위한 최고의 실전 대비서\n‘2024 빅데이...
4,Step by Step CRM을 위한 파이썬 머신러닝 (빅 데이터 분석 자격증 머신...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_394909...,김형수,30000,프레딕스,20230501,9791195511792,"본서는 파이썬을 전혀 모르는 사람도, 프로그래밍을 전혀 해보지 않은 사람도 단계적으..."
...,...,...,...,...,...,...,...,...,...
95,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
96,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
97,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
98,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
99,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

# 네이버 API로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답에서 total을 찾아서 display로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* start가 1, 101, 201, 301 처럼 변경되어야 함, start의 max값은 1000
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 append된 데이터 프레임을 1개로 합침

# for문을 이용해서 전체 페이지 가져오기

In [10]:
keyword = input("검색할 키워드를 입력해 주세요: ")

검색할 키워드를 입력해 주세요: 파이썬

In [11]:
all_data = []

In [12]:
url = "https://openapi.naver.com/v1/search/book.json"
Client_Id = "uk7phJIAYBDY5KptX5ev"
Client_Secret = "cnGUx6svh_"
headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
payload = dict(query=keyword, display=100, start=1, sort="sim")
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
data = r.json()
n_data = data['total']
total_pages = (int(data['total'])//100)+1
print("전체 검색 데이터 수: ", n_data, "검색할 페이지 수:", total_pages)
result_df = json_unpack(data)
all_data.append(result_df)

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12

In [14]:
start = 101
for page in range(total_pages):
    print(f"{page+1}/{total_pages} 수집 중", end="\r")
    url = "https://openapi.naver.com/v1/search/book.json"
    Client_Id = "uk7phJIAYBDY5KptX5ev"
    Client_Secret = "cnGUx6svh_"
    headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
    payload = dict(query=keyword, display=100, start=start, sort="sim")
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
#     print("전체 검색 데이터 수: ", n_data, "검색할 페이지 수:", total_pages)
    result_df = json_unpack(data)
    all_data.append(result_df)
    if start == 1000:
        break
    elif start < 901:
        start += 100
    elif start == 901:
        start += 99

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=101&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=201&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=301&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=401&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=501&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=601&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=701&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=801&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=901&sort=sim
200
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200

In [15]:
len(all_data)

11

In [16]:
final_result = pd.concat(all_data)
final_result = final_result.reset_index(drop=True)
final_result

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
1095,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
1096,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
1097,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
1098,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
1099,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

# while문으로 데이터 모두 가져오기

In [ ]:
import requests
import pandas as pd

In [29]:
keyword = input("검색할 키워드를 입력해 주세요: ")

검색할 키워드를 입력해 주세요: 파이썬

In [30]:
all_data2 = []
start = 1
while True:
    url = "https://openapi.naver.com/v1/search/book.json"
    Client_Id = "uk7phJIAYBDY5KptX5ev"
    Client_Secret = "cnGUx6svh_"
    headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
    payload = dict(query=keyword, display=100, start=start, sort="sim")
    r = requests.get(url, params=payload, headers=headers)
    print(r.url)
    print(r.status_code)
    data = r.json()
    n_data = data['total']
    total_pages = (int(data['total'])//100)+1
    print("전체 검색 데이터 수: ", n_data, "검색할 페이지 수:", total_pages)
    result_df = json_unpack(data)
    all_data2.append(result_df)
    if start == 1000:
        break
    elif start < 901:
        start += 100
    elif start == 901:
        start += 99

https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12
https://openapi.naver.com/v1/search/book.json?query=%ED%8C%8C%EC%9D%B4%EC%8D%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  1113 검색할 페이지 수: 12

In [31]:
len(all_data2)

11

In [32]:
final_result2 = pd.concat(all_data2)
final_result2 = final_result2.reset_index(drop=True)
final_result2

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
1095,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
1096,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
1097,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
1098,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
1099,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

In [22]:
final_result2.to_csv("네이버검색_책_파이썬.csv", encoding='utf-8-sig', index=False)

# 뉴스, 블로그, 책 한번에 검색해서 저장하기

In [26]:
keyword = input("검색할 키워드를 입력해 주세요: ")

검색할 키워드를 입력해 주세요: 핀테크

In [28]:
all_data3 = []

for category in ['blog', 'news', 'book']:
    start = 1
    while True:
        url = f"https://openapi.naver.com/v1/search/{category}.json"
        Client_Id = "uk7phJIAYBDY5KptX5ev"
        Client_Secret = "cnGUx6svh_"
        headers = {"X-Naver-Client-Id" : Client_Id, "X-Naver-Client-Secret" : Client_Secret}
        payload = dict(query=keyword, display=100, start=start, sort="sim")
        r = requests.get(url, params=payload, headers=headers)
        print(r.url)
        print(r.status_code)
        data = r.json()
        n_data = data['total']
        total_pages = (int(data['total'])//100)+1
        print("전체 검색 데이터 수: ", n_data, "검색할 페이지 수:", total_pages)
        result_df = json_unpack(data)
        all_data3.append(result_df)
        if start == 1000:
            break
        elif start < 901:
            start += 100
        elif start == 901:
            start += 99
final_result3 = pd.concat(all_data3)
final_result3 = final_result3.reset_index(drop=True)
final_result3

https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  456149 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  456148 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  456151 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  456148 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  456148 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  456151 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  456148 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  456149 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  456150 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  456149 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/blog.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  456148 검색할 페이지 수: 4562
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/news.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  498066 검색할 페이지 수: 4981
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=101&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=201&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=301&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=401&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=501&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=601&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=701&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=801&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=901&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2
https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1000&sort=sim
200
전체 검색 데이터 수:  106 검색할 페이지 수: 2

,title,link,description,bloggername,bloggerlink,postdate,originallink,pubDate,image,author,discount,publisher,pubdate,isbn
0,<b>핀테크</b> 투자 후기,https://blog.naver.com/kan1687/223812724931,"<b>핀테크</b> 투자, 아직도 망설이고 계신가요? 여러분 혹시 이런 고민 해보...",우정잉♥,blog.naver.com/kan1687,20250329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[<b>핀테크</b>] 2024년 <b>핀테크</b> 업계 결산: 놀라운 3가지 변화,https://blog.naver.com/xoom777/223708685044,동안 <b>핀테크</b> 업계에는 예상치 못한 변화의 바람이 불었습니다. 한동안 주...,Ich fange an,blog.naver.com/xoom777,20241229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[인사이트 캠퍼스] 2025 동계 <b>핀테크</b> 캠프 (with 전주대학교...,https://blog.naver.com/fininsight/223734638126,전주대학교 친구들이 직접 여의도까지 방문하여 <b>핀테크</b>(FinTech)의 ...,핀인사이트 (Fininsight),blog.naver.com/fininsight,20250122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[AI <b>핀테크</b>] AI와 빅데이터로 금융 시장을 재편하는 <b>핀테크</...,https://blog.naver.com/jangpung_/223765345858,이제 대출도 AI가 하는 시대 출처 : 파가야 테크놀러지스 홈페이지 금융과 기술이 ...,낭만을 꿈꾸는 일상,blog.naver.com/jangpung_,20250218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대,https://blog.naver.com/jaso_/223736810791,IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대 I...,미국주식 퍼주마,blog.naver.com/jaso_,20250130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2301,"신남방 지역 주요국의 핀테크 발전과 협력방안: 인도, 태국, 말레이시아, 베트남, ...",https://search.shopping.naver.com/book/catalog...,이 책은 대외경제정책연구원의 신남방 지역 주요국의 핀테크 발전과 협력방안을 다룬 정...,NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_332340...,이충열^이종하^이선호,9000,대외경제정책연구원,20201231,9788932290201
2302,[CD] 2018 4차산업 기업.스타트업 주소록 - CD-ROM 1장 (가상현실·드...,https://search.shopping.naver.com/book/catalog...,"2018 4차산업 기업·스타트업 주소록 CD에는 4차 산업기술, 바이오헬스케어, 창...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_324666...,한국콘텐츠미디어,170100,한국콘텐츠미디어,20180921,9791155055663
2303,"4차산업 기업·스타트업 주소록(2023)(CD) (IOT, VR, 가상현실, 블록체...",https://search.shopping.naver.com/book/catalog...,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 18,460건, IT기업 상세정보...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_400602...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20230501,8809496290337
2304,"4차산업 기업·스타트업 주소록(2024)(CD) (3D프린터, IOT, VR, 가상...",https://search.shopping.naver.com/book/catalog...,"4차산업 기업·스타트업 주소록을 분야별, 지역별로 19,908건, IT기업 상세정보...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240326,9791172340209
2305,"전국 체험마을 주소록(2024)(CD) (3D프린터, IOT, VR, 가상현실, 드...",https://search.shopping.naver.com/book/catalog...,"전국 체험마을 주소록을 분야별, 지역별로 33,479건, 관광·여가산업 상세정보를 ...",NaN,NaN,NaN,NaN,NaN,https://shopping-phinf.pstatic.net/main_466775...,한국콘텐츠미디어 편집부,215100,한국콘텐츠미디어,20240322,9791172340193