# xml: html처럼 태그 기반으로 자료를 저장한 포맷
* xml parser를 통해서 str을 xml로 변환하는 작업이 필요
* xml로 변환이 되면 태그 기반으로 자료를 찾아서 정리
* 태그에서 자료를 추출할 때는 beautifulsoup이라는 라이브러리를 이용

In [1]:
import os
import time
import requests
import pandas as pd

In [4]:
url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
payload = dict(serviceKey=service_key, numOfRows=20, pageNo=1, dataType="json")
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.json()

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=20&pageNo=1&dataType=JSON
200

In [5]:
response

{'header': {'resultCode': '00', 'resultMsg': '정상'},
 'body': {'pageNo': 1,
  'totalCount': 18,
  'numOfRows': 20,
  'items': [{'bssYmdStart': '20250310',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '산업은행',
    'callCenter': '1588-1500'},
   {'bssYmdStart': '20250310',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '제주은행',
    'callCenter': '1588-0079'},
   {'bssYmdStart': '20250310',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': 'SC은행',
    'callCenter': '1588-1599'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.89',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '전북은행',
    'callCenter': '1588-4477'},
   {'bssYmdStart': '20250310',
    'interest4_1': '0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '수협은행',
    'callCenter': '1588-1515'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.26',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '우리은행',
    'callCenter': '1599-5000'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.64',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '경남은행',
    'callCenter': '1588-8585'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.5',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '카카오뱅크',
    'callCenter': '1599-3333'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.38',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '아이엠뱅크',
    'callCenter': '1588-5050'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.18',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '하나은행',
    'callCenter': '1599-1111'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.74',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '토스뱅크',
    'callCenter': '1661-7654'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.7',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '케이뱅크',
    'callCenter': '1522-1000'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.89',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '국민은행',
    'callCenter': '1644-9999'},
   {'bssYmdStart': '20250310',
    'interest4_1': '3.84',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '부산은행',
    'callCenter': '1588-6200'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.05',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '농협은행',
    'callCenter': '1588-2100'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.0',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '기업은행',
    'callCenter': '1566-2566'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.11',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '광주은행',
    'callCenter': '1600-4000'},
   {'bssYmdStart': '20250310',
    'interest4_1': '4.07',
    'interest3_2': '0',
    'interest4_2': '0',
    'interest2_1': '0',
    'interest1_2': '0',
    'interest3_1': '0',
    'interest2_2': '0',
    'interest1_1': '0',
    'bssYmdEnd': '20250316',
    'organId': '신한은행',
    'callCenter': '1599-8000'}]}}

In [4]:
response['body']['totalCount']

18

In [6]:
len(response['body']['items'])

18

In [9]:
response['body']['items'][0]

{'bssYmdStart': '20250310',
 'interest4_1': '0',
 'interest3_2': '0',
 'interest4_2': '0',
 'interest2_1': '0',
 'interest1_2': '0',
 'interest3_1': '0',
 'interest2_2': '0',
 'interest1_1': '0',
 'bssYmdEnd': '20250316',
 'organId': '산업은행',
 'callCenter': '1588-1500'}

In [12]:
result = {}
for item in response['body']['items']:
    for key, value in item.items():
        result.setdefault(key, []).append(value)
df = pd.DataFrame(result)

In [13]:
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

# xml로 가져오기

In [14]:
url = "http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list"
service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
payload = dict(serviceKey=service_key, numOfRows=20, pageNo=1, dataType="xml")
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.text

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=20&pageNo=1&dataType=xml
200

In [15]:
response

'<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>20</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>'

* xml로 데이터를 받으면 처음에는 단순 문자열로 받게 된다.
* 문자열을 xml 문서로 변환해야 함
* beautifulsoup을 이용해 변환
* beautifulsoup의 메서드인 select_one을 이용해 css 셀렉터 기반으로 데이터가 위치한 태그를 찾아서 내용 추출

# BeautifulSoup
* https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 참고
* pip install beautifulsoup4
* from bs4 import BeautifulSoup as bs
* find, find_all 함수: xml, html에서 태그 기반으로 내용을 찾음
* select, select_one 함수: xml, html에서 css selector 기반으로 내용을 찾음
* find_all, select는 해당 태그나 css selector를 가진 부분으로 모두 찾아서 list로 반환
* find, select_one은 여러 태그나 css selector 중에서 가장 먼저 나오는 태그/selector를 한 개만 찾아줌
* 찾아온 태그 .name: 태그 이름 반환
* 찾아온 태그 .text, .string: 태그 안쪽의 텍스트 반환

In [16]:
# !pip install beautifulsoup4

In [17]:
from bs4 import BeautifulSoup as bs

In [19]:
soup = bs(response, 'xml')
soup

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>20</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>

In [20]:
soup.select_one("resultCode")

In [25]:
items = soup.select_one('items')
item = items.select("item")

In [26]:
item

[<item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item>,
 <item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item>]

In [33]:
for tag in items.select_one("item"):
    print(tag.name)

bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

In [34]:
items = soup.select_one('items')
bssYmdStart_list = items.select("bssYmdStart")
interest4_1_list = items.select("interest4_1")
interest3_2_list = items.select("interest3_2")
interest4_2_list = items.select("interest4_2")
interest2_1_list = items.select("interest2_1")
interest1_2_list = items.select("interest1_2")
interest3_1_list = items.select("interest3_1")
interest2_2_list = items.select("interest2_2")
interest1_1_list = items.select("interest1_1")
bssYmdEnd_list = items.select("bssYmdEnd")
organId_list = items.select("organId")
callCenter_list = items.select("callCenter")

In [40]:
tag_list = [bssYmdStart_list, interest4_1_list, interest3_2_list, interest4_2_list, interest2_1_list, interest1_2_list, interest3_1_list, interest2_2_list, interest1_1_list, bssYmdEnd_list, organId_list, callCenter_list]

In [41]:
result = {}
for lists in tag_list:
    for item in lists:
        result.setdefault(item.name, []).append(item.text)
result

{'bssYmdStart': ['20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310'],
 'interest4_1': ['0',
  '0',
  '0',
  '4.89',
  '0',
  '4.26',
  '4.64',
  '3.5',
  '3.38',
  '4.18',
  '3.74',
  '3.7',
  '3.89',
  '3.84',
  '4.05',
  '4.0',
  '4.11',
  '4.07'],
 'interest3_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest4_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest3_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'bssYmdEnd': ['20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316'],
 'organId': ['산업은행',
  '제주은행',
  'SC은행',
  '전북은행',
  '수협은행',
  '우리은행',
  '경남은행',
  '카카오뱅크',
  '아이엠뱅크',
  '하나은행',
  '토스뱅크',
  '케이뱅크',
  '국민은행',
  '부산은행',
  '농협은행',
  '기업은행',
  '광주은행',
  '신한은행'],
 'callCenter': ['1588-1500',
  '1588-0079',
  '1588-1599',
  '1588-4477',
  '1588-1515',
  '1599-5000',
  '1588-8585',
  '1599-3333',
  '1588-5050',
  '1599-1111',
  '1661-7654',
  '1522-1000',
  '1644-9999',
  '1588-6200',
  '1588-2100',
  '1566-2566',
  '1600-4000',
  '1599-8000']}

In [42]:
final_df = pd.DataFrame(result)
final_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

# 반복문으로 태그를 자동 추출해서 만들기

In [50]:
result = {}
for item in soup.select("items"):
    for tags in item:
        for tag in tags:
            result.setdefault(tag.name, []).append(tag.text)
result
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

In [62]:
result = {}
for tags in soup.select("item"):
    for tag in tags:
        result.setdefault(tag.name, []).append(tag.text)
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

In [53]:
for tag in soup.select("items")[0]:
    for key in tag:
        print(key.name, key.text)

bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 산업은행
callCenter 1588-1500
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 제주은행
callCenter 1588-0079
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId SC은행
callCenter 1588-1599
bssYmdStart 20250310
interest4_1 4.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 전북은행
callCenter 1588-4477
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 수협은행
callCenter 1588-1515
bssYmdStart 20250310
interest4_1 4.26
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 우리은행
callCenter 1599-5000
bssYmdStart 20250310
interest4_1 4.64
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 경남은행
callCenter 1588-8585
bssYmdStart 20250310
interest4_1 3.5
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 카카오뱅크
callCenter 1599-3333
bssYmdStart 20250310
interest4_1 3.38
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 아이엠뱅크
callCenter 1588-5050
bssYmdStart 20250310
interest4_1 4.18
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 하나은행
callCenter 1599-1111
bssYmdStart 20250310
interest4_1 3.74
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 토스뱅크
callCenter 1661-7654
bssYmdStart 20250310
interest4_1 3.7
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 케이뱅크
callCenter 1522-1000
bssYmdStart 20250310
interest4_1 3.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 국민은행
callCenter 1644-9999
bssYmdStart 20250310
interest4_1 3.84
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 부산은행
callCenter 1588-6200
bssYmdStart 20250310
interest4_1 4.05
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 농협은행
callCenter 1588-2100
bssYmdStart 20250310
interest4_1 4.0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 기업은행
callCenter 1566-2566
bssYmdStart 20250310
interest4_1 4.11
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 광주은행
callCenter 1600-4000
bssYmdStart 20250310
interest4_1 4.07
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 신한은행
callCenter 1599-8000

# xml에 있는 모든 key를 추출하기

In [60]:
tag_names = []
for items in soup.select("item"):
    for item in items:
        tag_names.append(item.name)
tag_names

['bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter']

# 집합자료형 set : 중복 없는 데이터 집합 만들기

In [61]:
tags = set(tag_names)
tags

{'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'organId'}

# 공공데이터 서민대출 데이터 수집
* 금융위원회_서민금융상품기본정보

# json 데이터 정리하기

In [3]:
import os
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs

In [4]:
url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
payload = dict(serviceKey=service_key, numOfRows=10, pageNo=1, resultType="json")
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.json()

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=10&pageNo=1&resultType=json
200

In [5]:
response

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 4741,
   'items': {'item': [{'basYm': '202503',
      'snq': '1',
      'finPrdNm': '새희망홀씨Ⅱ',
      'lnLmt': '3500만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '은행별 상이',
      'maxDfrmTrm': '-',
      'maxRdptTrm': '-',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자',
      'instCtg': '시중은행',
      'ofrInstNm': '14개 취급은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하',
      'age': '없음',
      'incm': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)',
      'rsdArea': '-',
      'crdtSc': '신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
      'grnInst': '-',
      'jnMthd': '14개 취급은행 신청방법 문의',
      'rpymdCfe': '-',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)',
      'etcRefSbjc': '-',
      'hdlInst': '취급 은행(14개)',
      'cnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
      'rltSite': '취급은행 홈페이지',
      'tgtFltr': '근로자',
      'hdlInstDtlVw': '취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '2',
      'finPrdNm': '징검다리론',
      'lnLmt': '3000만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '5년',
      'maxDfrmTrm': '1년',
      'maxRdptTrm': '4년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 대학생·청년, 채무조정자, 금융취약계층',
      'instCtg': '시중은행',
      'ofrInstNm': '15개 취급은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '4대 서민금융상품(새희망홀씨, 햇살론, 미소금융, 바꿔드림론)을 성실상환한 자1) 4대 서민금융상품 중 어느 하나를 2년 이상 거래한 후 해당 대출 원금의 75% 이상을 상환한 자 또는 거래기간에 상관없이 전액상환한 자2) CB신용평점: 상위 80%',
      'age': '없음',
      'incm': '없음',
      'rsdArea': '-',
      'crdtSc': 'CB신용평점: 상위 80%',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급은행 콜센터',
      'grnInst': '-',
      'jnMthd': '10개 취급은행 방문 또는 신청방법 문의',
      'rpymdCfe': None,
      'lnIcdcst': None,
      'ovItrYr': None,
      'prftAddIrtCond': '사회적 취약계층에 대한 금리 우대',
      'etcRefSbjc': None,
      'hdlInst': '취급 은행(10개)',
      'cnpl': '취급은행 콜센터',
      'rltSite': '취급은행 홈페이지',
      'tgtFltr': '근로자, 대학생·청년, 채무조정자, 금융취약계층',
      'hdlInstDtlVw': '취급은행(국민, 우리, 신한, 하나, SC, 기업, 수협, 부산, 경남, 광주)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '기관 문의',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '3',
      'finPrdNm': '우리지역 氣-Up 서포트론(영세 소기업,소상공인)',
      'lnLmt': '5,00010,000 (코로나 19 피해 소기업, 소상공인)',
      'irtCtg': '변동금리',
      'irt': '6.27~8.97%',
      'maxTotLnTrm': '5년',
      'maxDfrmTrm': '1년',
      'maxRdptTrm': '4년',
      'rdptMthd': '원금균등분할상환',
      'usge': '운영·시설',
      'trgt': '소기업, 소상공인',
      'instCtg': '시중은행',
      'ofrInstNm': 'BNK경남은행',
      'rsdAreaPamtEqltIstm': '경남, 울산',
      'suprTgtDtlCond': '신용보증신청 접수일 현재 사업자등록 후 가동(영업)중으로서 지역보증재단의 신용보증서를 발급받은 소기업ㆍ소상공인① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상의 소기업ㆍ소상공인 등 금융소외계층② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상의 소기업ㆍ소상공인 중 코로나 19로 인해 피해를 입은 경우※ 보증 가능여부는 재단에서 확인 가능함.※ CB평점구간 : 재단에서 보유하고 있는 NICE CB사의 평점구간※ 금융기관 신용관리관리 대상자 등 여신 부적격자에 대하여 대출이 제한될 수 있음',
      'age': '없음',
      'incm': '없음',
      'rsdArea': '-',
      'crdtSc': '① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1588-85851600-8585',
      'grnInst': '지역신용보증재단',
      'jnMthd': 'BNK경남은행 지점 문의 및 방문',
      'rpymdCfe': '대출취급 후 3년 경과시 면제대출잔여기간 1년 이상 1.6%대출잔여기간 1년 미만 및 할부상환방식일 경우 1.3%',
      'lnIcdcst': '(1) 인지세 : 인지세법에 의해 대출약정 체결시 납부하는 세금으로 대출금액에 따라 세액이 차등 적용되며, 각 50%씩 고객과 은행이 부담합니다.(2) 신용보증서 발급 수수료(고객께서 보증재단에 납부, 고객부담)',
      'ovItrYr': '대출금리+3.0%p (최고 연 15%)',
      'prftAddIrtCond': '(경남은행 계좌 BC가맹점 결제계좌 가입 및 입금) 0.2%p, (본인 신용카드(체크, 가족카드 포함) 이용액(매출표 접수기준)의 최근 3개월(대출취급일의 익월부터 산정) 평균 이용액이 월 평균 50만원 이상인 경우(신규 및 기존 포함)) 0.1%p',
      'etcRefSbjc': '-',
      'hdlInst': 'BNK경남은행',
      'cnpl': '1588-85851600-8585',
      'rltSite': 'https://www.knbank.co.kr/ib20/mnu/FPMLON050101000?ib20_wc=FPMLON210LSTV00M:FPMLON231DETV00M&FNC_PRD_NO=0000202720&FNC_PRD_DIS_CD=04&DUP_CHK=N&ib20_redirect_org_mnu=FPMCOM990000000',
      'tgtFltr': '소기업, 소상공인',
      'hdlInstDtlVw': 'BNK경남은행 전국 지점',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '4',
      'finPrdNm': '경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)',
      'lnLmt': '9000만원',
      'irtCtg': '변동금리',
      'irt': '은행별 상이',
      'maxTotLnTrm': '임대차계약기간 이내 최대 2년',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '0년',
      'rdptMthd': '일시상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'BNK경남은행',
      'rsdAreaPamtEqltIstm': '경남',
      'suprTgtDtlCond': '- 아래 요건을 모두 충족1) 경상남도에 주소를 두고 있거나, 대출신청 후 1개월 이내 전입신고 예정인 자2) 신청일 기준 만19세 이상 34세 이하인 청년3) 본인, 배우자, 자녀가 주거급여 대상자가 아니고 무주택인 자4) 다음의 어느 하나에 해당하는 경우  ① 대학(원)생, 취업준비생 등 무소득자 : 부모 합산 연소득 7천만원 이하 또는 부부합산 연소득 6천만원 이하  ② 사회초년생(한 직장에서 5년미만 근무하는 자/자영업자임을 증빙한 지역세대원) : 본인 연소득 4천5백만원 이하 또는 부부합산 연소득 6천만원 이하인 경우 5) 신청인 본인이 주거할 목적으로 경상남도에 소재한 임차보증금 1억원 이하, 전용면적 60 ㎡ 이하인 주택, 아파트, 오피스텔 등 주거용 건물에 임대차계약 체결 예정자 또는 계약체결 3개월 이내인 자',
      'age': '19세~34세',
      'incm': '본인 연소득 4500만원 이하 / 부부합산 연소득 6000만원 이하',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '무주택',
      'housAr': '60㎡',
      'lnTgtHous': '임차보증금 1억원 이하, 전용면적 60㎡ 이하의 주택 (경상남도 소재)',
      'rfrcCnpl': '경상남도 건축주택과 (Tel. 055-211-4374)',
      'grnInst': '주택금융공사',
      'jnMthd': '[경상남도 바로서비스누리집] 에서 본 사업 신청서 작성 → 제출서류 첨부 자격심사 통과 후 은행지점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '중도상환해약금(면제), 수입인지(건별 대출금액 5천만원 초과시 금액구간별 차등 부과_고객부담 50%), 주택금융공사 신용보증료(보증금액의 0.05%)',
      'ovItrYr': '-',
      'prftAddIrtCond': '은행자체 우대금리 : 급여이체, 카드사용 실적 등을 통한 우대금리 적용',
      'etcRefSbjc': '본인부담금리 = 은행 자체규정에 따른 금리 - 0.5%(우대금리) - 3%(경남도지원금리) - α(은행자체 우대금리)',
      'hdlInst': '농협은행, BNK경남은행',
      'cnpl': '경상남도 건축주택과 (Tel. 055-211-4374)',
      'rltSite': '경남 바로 서비스(https://baro.gyeongnam.go.kr/baro/serviceView.es?mid=a10202000000&service_no=183)',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '농협은행 경남지역지점, BNK 경남은행 경남지역지점(지역 농？축협은 대출 미취급)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '5',
      'finPrdNm': 'i-ONE근로자생활안정자금대출',
      'lnLmt': '1000만원',
      'irtCtg': '고정금리',
      'irt': '1.5 / 2.6 / 1.0 / 3.0',
      'maxTotLnTrm': '근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년, 8년요양급여비 : 5년직업훈련생계비 : 4년, 6년, 8년재직근로자의 대학학자금 : 7년, 8년, 9년, 10년, 11년',
      'maxDfrmTrm': '6년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '근로복지공단으로부터 신용보증결정 통보를 받은 고객※대출제외대상-은행연합회 신용정보 등재된 고객-대출신청일 현재 당행 대출금 또는 신용카드 연체중인 고객-재외국민, 외국인, 해외체류자',
      'age': '없음',
      'incm': '_',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '근로복지공단',
      'jnMthd': '영업점, 인터넷뱅킹, i-ONE뱅크',
      'rpymdCfe': '없음',
      'lnIcdcst': '▶ 신용보증료: 대출실행시 보증료를 차감한 후 고객이 요청한 당행 본인명의 예금계좌에 입금   ▶ 보증료: 근로자생활안정자금 연 0.9%, 그 외 연 1.00%',
      'ovItrYr': '여신이자율에 연체가산금리 연 3%를 더하여 적용. 단, 최고지연배상금률은 연 11%',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '대출종류별 확정금리 적용 (단, 공단이 별도로 정하여 통보하는 경우 그에 따른다)- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%- 직업훈련생계비 : 연 1.0%- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp?lncd=02&grcd=21&tmcd=209&pdcd=0001&wvcd=&i_trns_biz_kncd=',
      'tgtFltr': '근로자',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '6',
      'finPrdNm': 'IBK청년전·월세대출 (전세)',
      'lnLmt': '20000만원',
      'irtCtg': '고정금리, 변동금리',
      'irt': '3.8~4.3%',
      'maxTotLnTrm': '3년',
      'maxDfrmTrm': '3년',
      'maxRdptTrm': '0년',
      'rdptMthd': '만기일시상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
      'age': '34세 이하',
      'incm': '본인과 배우자의 합산 소득이 7천만원 이하인 자',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '한국주택금융공사',
      'jnMthd': '영업점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
      'ovItrYr': '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '7',
      'finPrdNm': 'IBK청년전·월세대출 (월세)',
      'lnLmt': '1200만원',
      'irtCtg': '변동금리',
      'irt': '4.34%',
      'maxTotLnTrm': '11, 13년',
      'maxDfrmTrm': '8년',
      'maxRdptTrm': '3, 5년',
      'rdptMthd': '원금균등분할상환',
      'usge': '주거',
      'trgt': '근로자, 사업자, 청년',
      'instCtg': '시중은행',
      'ofrInstNm': 'IBK기업은행',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
      'age': '34세 이하',
      'incm': '본인과 배우자의 합산 소득이 7천만원 이하인 자',
      'rsdArea': '-',
      'crdtSc': '-',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '1566-2566',
      'grnInst': '한국주택금융공사',
      'jnMthd': '영업점 방문',
      'rpymdCfe': '없음',
      'lnIcdcst': '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
      'ovItrYr': '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%',
      'hdlInst': '기업은행',
      'cnpl': '1566-2566',
      'rltSite': 'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
      'tgtFltr': '근로자, 사업자, 청년',
      'hdlInstDtlVw': '기업은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '8',
      'finPrdNm': '사잇돌Ⅱ대출_표준',
      'lnLmt': '3000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 사업자, 연금소득자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 직업훈련생계비 : 연 1.0%',
      'hdlInst': '저축은행',
      'cnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0100.act',
      'tgtFltr': '근로자, 사업자, 연금소득자',
      'hdlInstDtlVw': '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '9',
      'finPrdNm': '사잇돌Ⅱ대출_대환형',
      'lnLmt': '2000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '근로자, 사업자, 연금소득자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
      'hdlInst': '저축은행',
      'cnpl': '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0300.act',
      'tgtFltr': '근로자, 사업자, 연금소득자',
      'hdlInstDtlVw': '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '상시',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'},
     {'basYm': '202503',
      'snq': '10',
      'finPrdNm': '사잇돌Ⅱ대출_채무조정졸업자',
      'lnLmt': '1000만원',
      'irtCtg': '변동금리',
      'irt': '~19.99%',
      'maxTotLnTrm': '5(최대 60개월, 보증기간 이내)',
      'maxDfrmTrm': '0년',
      'maxRdptTrm': '5년',
      'rdptMthd': '원(리)금균등분할상환',
      'usge': '생계',
      'trgt': '채무조정자',
      'instCtg': '민간기업',
      'ofrInstNm': 'SGI서울보증',
      'rsdAreaPamtEqltIstm': '전국',
      'suprTgtDtlCond': '- 소득수준 : 다음의 어느 하나에 해당하는 소득이 있는 자 - (근로소득)보증 신청일 현재 5개월 이상(유지) 재직자로서 연 소득이 12백만원 이상인 자 - (사업소득)보증 신청일 현재 4개월 이상(유지) 사업소득 발생자로서 연 소득이 6백만원 이상인 자 - (연금소득) 보증 신청일 현재 연금(국민연금, 공무원연금, 군인연금, 사학연금) 소득 1회 이상 수령자로서 연금 소득이 연 6백만원 이상인 자 -  기타조건 - 채무조정제도(개인워크아웃, 프리워크아웃, 개인회생)를 졸업한지 3년 이내인 자- 보험 청약일 현재 사잇돌 1, 2 대출’을 보유하고 있지 않은 자- 한국신용정보원을 통하여 확인되는 대부업체 대출보유건수가 1건 이내인 자',
      'age': '없음',
      'incm': '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
      'rsdArea': '-',
      'crdtSc': '없음',
      'anin': '-',
      'housHoldCnt': '-',
      'housAr': '-',
      'lnTgtHous': '-',
      'rfrcCnpl': '033-370-2627',
      'grnInst': 'SGI서울보증보험',
      'jnMthd': '취급 금융기관 방문, 서금원 맞춤대출 조회',
      'rpymdCfe': '없음',
      'lnIcdcst': '-',
      'ovItrYr': '-',
      'prftAddIrtCond': '-',
      'etcRefSbjc': '-',
      'hdlInst': '저축은행',
      'cnpl': '033-370-2627',
      'rltSite': 'https://www.fsb.or.kr/finloanconn_0400.act',
      'tgtFltr': '채무조정자',
      'hdlInstDtlVw': '취급저축은행',
      'prdExisYn': 'Y',
      'cv19Rfrc': '-',
      'prdCtg': '1',
      'prdNm': '대출상품',
      'cv19SuprCtg': '-',
      'cv19SuprCtn': '-',
      'cv19SuprTgtDtlCtn': '-',
      'mgmDln': '기관 문의',
      'prdCtg2': '-',
      'fileWrtDt': '202504010700'}]}}}}

In [6]:
total_page = response['response']['body']['totalCount'] // response['response']['body']['numOfRows'] + 1
total_page

474

In [9]:
response['response']['body']['items']['item'][0]

{'basYm': '202503',
 'snq': '1',
 'finPrdNm': '새희망홀씨Ⅱ',
 'lnLmt': '3500만원',
 'irtCtg': '변동금리',
 'irt': '은행별 상이',
 'maxTotLnTrm': '은행별 상이',
 'maxDfrmTrm': '-',
 'maxRdptTrm': '-',
 'rdptMthd': '원(리)금균등분할상환',
 'usge': '생계',
 'trgt': '근로자',
 'instCtg': '시중은행',
 'ofrInstNm': '14개 취급은행',
 'rsdAreaPamtEqltIstm': '전국',
 'suprTgtDtlCond': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하',
 'age': '없음',
 'incm': '연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)',
 'rsdArea': '-',
 'crdtSc': '신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자',
 'anin': '-',
 'housHoldCnt': '-',
 'housAr': '-',
 'lnTgtHous': '-',
 'rfrcCnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
 'grnInst': '-',
 'jnMthd': '14개 취급은행 신청방법 문의',
 'rpymdCfe': '-',
 'lnIcdcst': '-',
 'ovItrYr': '-',
 'prftAddIrtCond': '성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)',
 'etcRefSbjc': '-',
 'hdlInst': '취급 은행(14개)',
 'cnpl': '취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
 'rltSite': '취급은행 홈페이지',
 'tgtFltr': '근로자',
 'hdlInstDtlVw': '취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)',
 'prdExisYn': 'Y',
 'cv19Rfrc': '-',
 'prdCtg': '1',
 'prdNm': '대출상품',
 'cv19SuprCtg': '-',
 'cv19SuprCtn': '-',
 'cv19SuprTgtDtlCtn': '-',
 'mgmDln': '상시',
 'prdCtg2': '-',
 'fileWrtDt': '202504010700'}

In [10]:
result = {}
for item in response['response']['body']['items']['item']:
    for key, value in item.items():
        result.setdefault(key, []).append(value)
result

{'basYm': ['202503',
  '202503',
  '202503',
  '202503',
  '202503',
  '202503',
  '202503',
  '202503',
  '202503',
  '202503'],
 'snq': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
 'finPrdNm': ['새희망홀씨Ⅱ',
  '징검다리론',
  '우리지역 氣-Up 서포트론(영세 소기업,소상공인)',
  '경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)',
  'i-ONE근로자생활안정자금대출',
  'IBK청년전·월세대출 (전세)',
  'IBK청년전·월세대출 (월세)',
  '사잇돌Ⅱ대출_표준',
  '사잇돌Ⅱ대출_대환형',
  '사잇돌Ⅱ대출_채무조정졸업자'],
 'lnLmt': ['3500만원',
  '3000만원',
  '5,00010,000 (코로나 19 피해 소기업, 소상공인)',
  '9000만원',
  '1000만원',
  '20000만원',
  '1200만원',
  '3000만원',
  '2000만원',
  '1000만원'],
 'irtCtg': ['변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '고정금리',
  '고정금리, 변동금리',
  '변동금리',
  '변동금리',
  '변동금리',
  '변동금리'],
 'irt': ['은행별 상이',
  '은행별 상이',
  '6.27~8.97%',
  '은행별 상이',
  '1.5 / 2.6 / 1.0 / 3.0',
  '3.8~4.3%',
  '4.34%',
  '~19.99%',
  '~19.99%',
  '~19.99%'],
 'maxTotLnTrm': ['은행별 상이',
  '5년',
  '5년',
  '임대차계약기간 이내 최대 2년',
  '근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년, 8년요양급여비 : 5년직업훈련생계비 : 4년, 6년, 8년재직근로자의 대학학자금 : 7년, 8년, 9년, 10년, 11년',
  '3년',
  '11, 13년',
  '5(최대 60개월, 보증기간 이내)',
  '5(최대 60개월, 보증기간 이내)',
  '5(최대 60개월, 보증기간 이내)'],
 'maxDfrmTrm': ['-', '1년', '1년', '0년', '6년', '3년', '8년', '0년', '0년', '0년'],
 'maxRdptTrm': ['-', '4년', '4년', '0년', '5년', '0년', '3, 5년', '5년', '5년', '5년'],
 'rdptMthd': ['원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원금균등분할상환',
  '일시상환',
  '원(리)금균등분할상환',
  '만기일시상환',
  '원금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환',
  '원(리)금균등분할상환'],
 'usge': ['생계', '생계', '운영·시설', '주거', '생계', '주거', '주거', '생계', '생계', '생계'],
 'trgt': ['근로자',
  '근로자, 대학생·청년, 채무조정자, 금융취약계층',
  '소기업, 소상공인',
  '근로자, 사업자, 청년',
  '근로자',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 연금소득자',
  '근로자, 사업자, 연금소득자',
  '채무조정자'],
 'instCtg': ['시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '시중은행',
  '민간기업',
  '민간기업',
  '민간기업'],
 'ofrInstNm': ['14개 취급은행',
  '15개 취급은행',
  'BNK경남은행',
  'BNK경남은행',
  'IBK기업은행',
  'IBK기업은행',
  'IBK기업은행',
  'SGI서울보증',
  'SGI서울보증',
  'SGI서울보증'],
 'rsdAreaPamtEqltIstm': ['전국',
  '전국',
  '경남, 울산',
  '경남',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국',
  '전국'],
 'suprTgtDtlCond': ['연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하',
  '4대 서민금융상품(새희망홀씨, 햇살론, 미소금융, 바꿔드림론)을 성실상환한 자1) 4대 서민금융상품 중 어느 하나를 2년 이상 거래한 후 해당 대출 원금의 75% 이상을 상환한 자 또는 거래기간에 상관없이 전액상환한 자2) CB신용평점: 상위 80%',
  '신용보증신청 접수일 현재 사업자등록 후 가동(영업)중으로서 지역보증재단의 신용보증서를 발급받은 소기업ㆍ소상공인① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상의 소기업ㆍ소상공인 등 금융소외계층② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상의 소기업ㆍ소상공인 중 코로나 19로 인해 피해를 입은 경우※ 보증 가능여부는 재단에서 확인 가능함.※ CB평점구간 : 재단에서 보유하고 있는 NICE CB사의 평점구간※ 금융기관 신용관리관리 대상자 등 여신 부적격자에 대하여 대출이 제한될 수 있음',
  '- 아래 요건을 모두 충족1) 경상남도에 주소를 두고 있거나, 대출신청 후 1개월 이내 전입신고 예정인 자2) 신청일 기준 만19세 이상 34세 이하인 청년3) 본인, 배우자, 자녀가 주거급여 대상자가 아니고 무주택인 자4) 다음의 어느 하나에 해당하는 경우  ① 대학(원)생, 취업준비생 등 무소득자 : 부모 합산 연소득 7천만원 이하 또는 부부합산 연소득 6천만원 이하  ② 사회초년생(한 직장에서 5년미만 근무하는 자/자영업자임을 증빙한 지역세대원) : 본인 연소득 4천5백만원 이하 또는 부부합산 연소득 6천만원 이하인 경우 5) 신청인 본인이 주거할 목적으로 경상남도에 소재한 임차보증금 1억원 이하, 전용면적 60 ㎡ 이하인 주택, 아파트, 오피스텔 등 주거용 건물에 임대차계약 체결 예정자 또는 계약체결 3개월 이내인 자',
  '근로복지공단으로부터 신용보증결정 통보를 받은 고객※대출제외대상-은행연합회 신용정보 등재된 고객-대출신청일 현재 당행 대출금 또는 신용카드 연체중인 고객-재외국민, 외국인, 해외체류자',
  '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
  '대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.',
  '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
  '중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)',
  '- 소득수준 : 다음의 어느 하나에 해당하는 소득이 있는 자 - (근로소득)보증 신청일 현재 5개월 이상(유지) 재직자로서 연 소득이 12백만원 이상인 자 - (사업소득)보증 신청일 현재 4개월 이상(유지) 사업소득 발생자로서 연 소득이 6백만원 이상인 자 - (연금소득) 보증 신청일 현재 연금(국민연금, 공무원연금, 군인연금, 사학연금) 소득 1회 이상 수령자로서 연금 소득이 연 6백만원 이상인 자 -  기타조건 - 채무조정제도(개인워크아웃, 프리워크아웃, 개인회생)를 졸업한지 3년 이내인 자- 보험 청약일 현재 사잇돌 1, 2 대출’을 보유하고 있지 않은 자- 한국신용정보원을 통하여 확인되는 대부업체 대출보유건수가 1건 이내인 자'],
 'age': ['없음',
  '없음',
  '없음',
  '19세~34세',
  '없음',
  '34세 이하',
  '34세 이하',
  '없음',
  '없음',
  '없음'],
 'incm': ['연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)',
  '없음',
  '없음',
  '본인 연소득 4500만원 이하 / 부부합산 연소득 6000만원 이하',
  '_',
  '본인과 배우자의 합산 소득이 7천만원 이하인 자',
  '본인과 배우자의 합산 소득이 7천만원 이하인 자',
  '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
  '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산',
  '(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산'],
 'rsdArea': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'crdtSc': ['신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자',
  'CB신용평점: 상위 80%',
  '① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상',
  '없음',
  '없음',
  '없음',
  '-',
  '없음',
  '없음',
  '없음'],
 'anin': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'housHoldCnt': ['-', '-', '-', '무주택', '-', '-', '-', '-', '-', '-'],
 'housAr': ['-', '-', '-', '60㎡', '-', '-', '-', '-', '-', '-'],
 'lnTgtHous': ['-',
  '-',
  '-',
  '임차보증금 1억원 이하, 전용면적 60㎡ 이하의 주택 (경상남도 소재)',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-'],
 'rfrcCnpl': ['취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
  '취급은행 콜센터',
  '1588-85851600-8585',
  '경상남도 건축주택과 (Tel. 055-211-4374)',
  '1566-2566',
  '1566-2566',
  '1566-2566',
  '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
  '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
  '033-370-2627'],
 'grnInst': ['-',
  '-',
  '지역신용보증재단',
  '주택금융공사',
  '근로복지공단',
  '한국주택금융공사',
  '한국주택금융공사',
  'SGI서울보증보험',
  'SGI서울보증보험',
  'SGI서울보증보험'],
 'jnMthd': ['14개 취급은행 신청방법 문의',
  '10개 취급은행 방문 또는 신청방법 문의',
  'BNK경남은행 지점 문의 및 방문',
  '[경상남도 바로서비스누리집] 에서 본 사업 신청서 작성 → 제출서류 첨부 자격심사 통과 후 은행지점 방문',
  '영업점, 인터넷뱅킹, i-ONE뱅크',
  '영업점 방문',
  '영업점 방문',
  '취급 금융기관 방문, 서금원 맞춤대출 조회',
  '취급 금융기관 방문, 서금원 맞춤대출 조회',
  '취급 금융기관 방문, 서금원 맞춤대출 조회'],
 'rpymdCfe': ['-',
  None,
  '대출취급 후 3년 경과시 면제대출잔여기간 1년 이상 1.6%대출잔여기간 1년 미만 및 할부상환방식일 경우 1.3%',
  '없음',
  '없음',
  '없음',
  '없음',
  '없음',
  '없음',
  '없음'],
 'lnIcdcst': ['-',
  None,
  '(1) 인지세 : 인지세법에 의해 대출약정 체결시 납부하는 세금으로 대출금액에 따라 세액이 차등 적용되며, 각 50%씩 고객과 은행이 부담합니다.(2) 신용보증서 발급 수수료(고객께서 보증재단에 납부, 고객부담)',
  '중도상환해약금(면제), 수입인지(건별 대출금액 5천만원 초과시 금액구간별 차등 부과_고객부담 50%), 주택금융공사 신용보증료(보증금액의 0.05%)',
  '▶ 신용보증료: 대출실행시 보증료를 차감한 후 고객이 요청한 당행 본인명의 예금계좌에 입금   ▶ 보증료: 근로자생활안정자금 연 0.9%, 그 외 연 1.00%',
  '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
  '5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)',
  '-',
  '-',
  '-'],
 'ovItrYr': ['-',
  None,
  '대출금리+3.0%p (최고 연 15%)',
  '-',
  '여신이자율에 연체가산금리 연 3%를 더하여 적용. 단, 최고지연배상금률은 연 11%',
  '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
  '대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)',
  '-',
  '-',
  '-'],
 'prftAddIrtCond': ['성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)',
  '사회적 취약계층에 대한 금리 우대',
  '(경남은행 계좌 BC가맹점 결제계좌 가입 및 입금) 0.2%p, (본인 신용카드(체크, 가족카드 포함) 이용액(매출표 접수기준)의 최근 3개월(대출취급일의 익월부터 산정) 평균 이용액이 월 평균 50만원 이상인 경우(신규 및 기존 포함)) 0.1%p',
  '은행자체 우대금리 : 급여이체, 카드사용 실적 등을 통한 우대금리 적용',
  '-',
  '-',
  '-',
  '-',
  '-',
  '-'],
 'etcRefSbjc': ['-',
  None,
  '-',
  '본인부담금리 = 은행 자체규정에 따른 금리 - 0.5%(우대금리) - 3%(경남도지원금리) - α(은행자체 우대금리)',
  '대출종류별 확정금리 적용 (단, 공단이 별도로 정하여 통보하는 경우 그에 따른다)- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%- 직업훈련생계비 : 연 1.0%- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
  '- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%',
  '- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%',
  '- 직업훈련생계비 : 연 1.0%',
  '- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%',
  '-'],
 'hdlInst': ['취급 은행(14개)',
  '취급 은행(10개)',
  'BNK경남은행',
  '농협은행, BNK경남은행',
  '기업은행',
  '기업은행',
  '기업은행',
  '저축은행',
  '저축은행',
  '저축은행'],
 'cnpl': ['취급은행 콜센터, 서민금융콜센터 (국번없이)1397',
  '취급은행 콜센터',
  '1588-85851600-8585',
  '경상남도 건축주택과 (Tel. 055-211-4374)',
  '1566-2566',
  '1566-2566',
  '1566-2566',
  '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
  '취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397',
  '033-370-2627'],
 'rltSite': ['취급은행 홈페이지',
  '취급은행 홈페이지',
  'https://www.knbank.co.kr/ib20/mnu/FPMLON050101000?ib20_wc=FPMLON210LSTV00M:FPMLON231DETV00M&FNC_PRD_NO=0000202720&FNC_PRD_DIS_CD=04&DUP_CHK=N&ib20_redirect_org_mnu=FPMCOM990000000',
  '경남 바로 서비스(https://baro.gyeongnam.go.kr/baro/serviceView.es?mid=a10202000000&service_no=183)',
  'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp?lncd=02&grcd=21&tmcd=209&pdcd=0001&wvcd=&i_trns_biz_kncd=',
  'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
  'https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp',
  'https://www.fsb.or.kr/finloanconn_0100.act',
  'https://www.fsb.or.kr/finloanconn_0300.act',
  'https://www.fsb.or.kr/finloanconn_0400.act'],
 'tgtFltr': ['근로자',
  '근로자, 대학생·청년, 채무조정자, 금융취약계층',
  '소기업, 소상공인',
  '근로자, 사업자, 청년',
  '근로자',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 청년',
  '근로자, 사업자, 연금소득자',
  '근로자, 사업자, 연금소득자',
  '채무조정자'],
 'hdlInstDtlVw': ['취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)',
  '취급은행(국민, 우리, 신한, 하나, SC, 기업, 수협, 부산, 경남, 광주)',
  'BNK경남은행 전국 지점',
  '농협은행 경남지역지점, BNK 경남은행 경남지역지점(지역 농？축협은 대출 미취급)',
  '기업은행',
  '기업은행',
  '기업은행',
  '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
  '취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)',
  '취급저축은행'],
 'prdExisYn': ['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y'],
 'cv19Rfrc': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'prdCtg': ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
 'prdNm': ['대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품',
  '대출상품'],
 'cv19SuprCtg': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'cv19SuprCtn': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'cv19SuprTgtDtlCtn': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'mgmDln': ['상시', '기관 문의', '상시', '상시', '상시', '상시', '상시', '상시', '상시', '기관 문의'],
 'prdCtg2': ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
 'fileWrtDt': ['202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700',
  '202504010700']}

In [12]:
page = 1
result_list = []
while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
    payload = dict(serviceKey=service_key, numOfRows=1000, pageNo=page, resultType="json")
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.json()
    total_page = response['response']['body']['totalCount'] // response['response']['body']['numOfRows'] + 1
    result = {}
    for item in response['response']['body']['items']['item']:
        for key, value in item.items():
            result.setdefault(key, []).append(value)
    df = pd.DataFrame(result)
    result_list.append(df)
    if page < total_page:
        page += 1
    else:
        break
        
result_df = pd.concat(result_list)
result_df = result_df.reset_index(drop=True)
result_df

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=1&resultType=json
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=2&resultType=json
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=3&resultType=json
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=4&resultType=json
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=5&resultType=json
200

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,None,1,대출상품,None,None,None,None,None,202502010700

# XML 데이터 정리하기

In [13]:
url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
payload = dict(serviceKey=service_key, numOfRows=10, pageNo=1, resultType="xml")
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.content
soup = bs(response, 'xml')
soup

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=10&pageNo=1&resultType=xml
200

<?xml version="1.0" encoding="utf-8"?>
<response>
<header>
<resultCode>00</resultCode>
<resultMsg>NORMAL SERVICE.</resultMsg>
</header>
<body>
<numOfRows>10</numOfRows>
<pageNo>1</pageNo>
<totalCount>4741</totalCount>
<items>
<item>
<basYm>202503</basYm>
<snq>1</snq>
<finPrdNm>새희망홀씨Ⅱ</finPrdNm>
<lnLmt>3500만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>은행별 상이</irt>
<maxTotLnTrm>은행별 상이</maxTotLnTrm>
<maxDfrmTrm>-</maxDfrmTrm>
<maxRdptTrm>-</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>14개 취급은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하) *23년 4월 기준 NICE 749점, KCB 700점 이하</suprTgtDtlCond>
<age>없음</age>
<incm>연소득 4천만원 이하 (개인신용평점 하위 100분의 20*이하는 5천만원 이하)</incm>
<rsdArea>-</rsdArea>
<crdtSc>신용평가회사의 개인신용평점이 하위 100분의 20에 해당하는자</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</rfrcCnpl>
<grnInst>-</grnInst>
<jnMthd>14개 취급은행 신청방법 문의</jnMthd>
<rpymdCfe>-</rpymdCfe>
<lnIcdcst>-</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>성실상환자, 사회적 취약계층(기초생활수급권자, 한부모가정, 다자녀가정, 다문화가정, 만 60세 이상 부모부양자, 청년층(만 29세 이하), 고령자(만 65세 이상), 장애인 등), 공신력 있는 금융교육기관에서 금융교육을 이수한 자에 대해 금리우대 (은행별 자율 결정)</prftAddIrtCond>
<etcRefSbjc>-</etcRefSbjc>
<hdlInst>취급 은행(14개)</hdlInst>
<cnpl>취급은행 콜센터, 서민금융콜센터 (국번없이)1397</cnpl>
<rltSite>취급은행 홈페이지</rltSite>
<tgtFltr>근로자</tgtFltr>
<hdlInstDtlVw>취급은행(국민, 신한, 우리, 기업, KEB하나, SC, 농협, 수협, 경남, 광주, 대구, 부산, 전북, 제주)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>2</snq>
<finPrdNm>징검다리론</finPrdNm>
<lnLmt>3000만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>은행별 상이</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>1년</maxDfrmTrm>
<maxRdptTrm>4년</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자, 대학생·청년, 채무조정자, 금융취약계층</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>15개 취급은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>4대 서민금융상품(새희망홀씨, 햇살론, 미소금융, 바꿔드림론)을 성실상환한 자1) 4대 서민금융상품 중 어느 하나를 2년 이상 거래한 후 해당 대출 원금의 75% 이상을 상환한 자 또는 거래기간에 상관없이 전액상환한 자2) CB신용평점: 상위 80%</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea>-</rsdArea>
<crdtSc>CB신용평점: 상위 80%</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>취급은행 콜센터</rfrcCnpl>
<grnInst>-</grnInst>
<jnMthd>10개 취급은행 방문 또는 신청방법 문의</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond>사회적 취약계층에 대한 금리 우대</prftAddIrtCond>
<etcRefSbjc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<hdlInst>취급 은행(10개)</hdlInst>
<cnpl>취급은행 콜센터</cnpl>
<rltSite>취급은행 홈페이지</rltSite>
<tgtFltr>근로자, 대학생·청년, 채무조정자, 금융취약계층</tgtFltr>
<hdlInstDtlVw>취급은행(국민, 우리, 신한, 하나, SC, 기업, 수협, 부산, 경남, 광주)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>기관 문의</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>3</snq>
<finPrdNm>우리지역 氣-Up 서포트론(영세 소기업,소상공인)</finPrdNm>
<lnLmt>5,00010,000 (코로나 19 피해 소기업, 소상공인)</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>6.27~8.97%</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>1년</maxDfrmTrm>
<maxRdptTrm>4년</maxRdptTrm>
<rdptMthd>원금균등분할상환</rdptMthd>
<usge>운영·시설</usge>
<trgt>소기업, 소상공인</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>BNK경남은행</ofrInstNm>
<rsdAreaPamtEqltIstm>경남, 울산</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>신용보증신청 접수일 현재 사업자등록 후 가동(영업)중으로서 지역보증재단의 신용보증서를 발급받은 소기업ㆍ소상공인① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상의 소기업ㆍ소상공인 등 금융소외계층② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상의 소기업ㆍ소상공인 중 코로나 19로 인해 피해를 입은 경우※ 보증 가능여부는 재단에서 확인 가능함.※ CB평점구간 : 재단에서 보유하고 있는 NICE CB사의 평점구간※ 금융기관 신용관리관리 대상자 등 여신 부적격자에 대하여 대출이 제한될 수 있음</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea>-</rsdArea>
<crdtSc>① 영세 소기업ㆍ소상공인 : CB평점구간 7구간 이상② 코로나19 피해 소기업ㆍ소상공인 : CB평점구간 8구간 이상</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>1588-85851600-8585</rfrcCnpl>
<grnInst>지역신용보증재단</grnInst>
<jnMthd>BNK경남은행 지점 문의 및 방문</jnMthd>
<rpymdCfe>대출취급 후 3년 경과시 면제대출잔여기간 1년 이상 1.6%대출잔여기간 1년 미만 및 할부상환방식일 경우 1.3%</rpymdCfe>
<lnIcdcst>(1) 인지세 : 인지세법에 의해 대출약정 체결시 납부하는 세금으로 대출금액에 따라 세액이 차등 적용되며, 각 50%씩 고객과 은행이 부담합니다.(2) 신용보증서 발급 수수료(고객께서 보증재단에 납부, 고객부담)</lnIcdcst>
<ovItrYr>대출금리+3.0%p (최고 연 15%)</ovItrYr>
<prftAddIrtCond>(경남은행 계좌 BC가맹점 결제계좌 가입 및 입금) 0.2%p, (본인 신용카드(체크, 가족카드 포함) 이용액(매출표 접수기준)의 최근 3개월(대출취급일의 익월부터 산정) 평균 이용액이 월 평균 50만원 이상인 경우(신규 및 기존 포함)) 0.1%p</prftAddIrtCond>
<etcRefSbjc>-</etcRefSbjc>
<hdlInst>BNK경남은행</hdlInst>
<cnpl>1588-85851600-8585</cnpl>
<rltSite>https://www.knbank.co.kr/ib20/mnu/FPMLON050101000?ib20_wc=FPMLON210LSTV00M:FPMLON231DETV00M&amp;FNC_PRD_NO=0000202720&amp;FNC_PRD_DIS_CD=04&amp;DUP_CHK=N&amp;ib20_redirect_org_mnu=FPMCOM990000000</rltSite>
<tgtFltr>소기업, 소상공인</tgtFltr>
<hdlInstDtlVw>BNK경남은행 전국 지점</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>4</snq>
<finPrdNm>경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)</finPrdNm>
<lnLmt>9000만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>은행별 상이</irt>
<maxTotLnTrm>임대차계약기간 이내 최대 2년</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>0년</maxRdptTrm>
<rdptMthd>일시상환</rdptMthd>
<usge>주거</usge>
<trgt>근로자, 사업자, 청년</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>BNK경남은행</ofrInstNm>
<rsdAreaPamtEqltIstm>경남</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>- 아래 요건을 모두 충족1) 경상남도에 주소를 두고 있거나, 대출신청 후 1개월 이내 전입신고 예정인 자2) 신청일 기준 만19세 이상 34세 이하인 청년3) 본인, 배우자, 자녀가 주거급여 대상자가 아니고 무주택인 자4) 다음의 어느 하나에 해당하는 경우  ① 대학(원)생, 취업준비생 등 무소득자 : 부모 합산 연소득 7천만원 이하 또는 부부합산 연소득 6천만원 이하  ② 사회초년생(한 직장에서 5년미만 근무하는 자/자영업자임을 증빙한 지역세대원) : 본인 연소득 4천5백만원 이하 또는 부부합산 연소득 6천만원 이하인 경우 5) 신청인 본인이 주거할 목적으로 경상남도에 소재한 임차보증금 1억원 이하, 전용면적 60 ㎡ 이하인 주택, 아파트, 오피스텔 등 주거용 건물에 임대차계약 체결 예정자 또는 계약체결 3개월 이내인 자</suprTgtDtlCond>
<age>19세~34세</age>
<incm>본인 연소득 4500만원 이하 / 부부합산 연소득 6000만원 이하</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>무주택</housHoldCnt>
<housAr>60㎡</housAr>
<lnTgtHous>임차보증금 1억원 이하, 전용면적 60㎡ 이하의 주택 (경상남도 소재)</lnTgtHous>
<rfrcCnpl>경상남도 건축주택과 (Tel. 055-211-4374)</rfrcCnpl>
<grnInst>주택금융공사</grnInst>
<jnMthd>[경상남도 바로서비스누리집] 에서 본 사업 신청서 작성 → 제출서류 첨부 자격심사 통과 후 은행지점 방문</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>중도상환해약금(면제), 수입인지(건별 대출금액 5천만원 초과시 금액구간별 차등 부과_고객부담 50%), 주택금융공사 신용보증료(보증금액의 0.05%)</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>은행자체 우대금리 : 급여이체, 카드사용 실적 등을 통한 우대금리 적용</prftAddIrtCond>
<etcRefSbjc>본인부담금리 = 은행 자체규정에 따른 금리 - 0.5%(우대금리) - 3%(경남도지원금리) - α(은행자체 우대금리)</etcRefSbjc>
<hdlInst>농협은행, BNK경남은행</hdlInst>
<cnpl>경상남도 건축주택과 (Tel. 055-211-4374)</cnpl>
<rltSite>경남 바로 서비스(https://baro.gyeongnam.go.kr/baro/serviceView.es?mid=a10202000000&amp;service_no=183)</rltSite>
<tgtFltr>근로자, 사업자, 청년</tgtFltr>
<hdlInstDtlVw>농협은행 경남지역지점, BNK 경남은행 경남지역지점(지역 농？축협은 대출 미취급)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>5</snq>
<finPrdNm>i-ONE근로자생활안정자금대출</finPrdNm>
<lnLmt>1000만원</lnLmt>
<irtCtg>고정금리</irtCtg>
<irt>1.5 / 2.6 / 1.0 / 3.0</irt>
<maxTotLnTrm>근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년, 8년요양급여비 : 5년직업훈련생계비 : 4년, 6년, 8년재직근로자의 대학학자금 : 7년, 8년, 9년, 10년, 11년</maxTotLnTrm>
<maxDfrmTrm>6년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>IBK기업은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>근로복지공단으로부터 신용보증결정 통보를 받은 고객※대출제외대상-은행연합회 신용정보 등재된 고객-대출신청일 현재 당행 대출금 또는 신용카드 연체중인 고객-재외국민, 외국인, 해외체류자</suprTgtDtlCond>
<age>없음</age>
<incm>_</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>1566-2566</rfrcCnpl>
<grnInst>근로복지공단</grnInst>
<jnMthd>영업점, 인터넷뱅킹, i-ONE뱅크</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>▶ 신용보증료: 대출실행시 보증료를 차감한 후 고객이 요청한 당행 본인명의 예금계좌에 입금   ▶ 보증료: 근로자생활안정자금 연 0.9%, 그 외 연 1.00%</lnIcdcst>
<ovItrYr>여신이자율에 연체가산금리 연 3%를 더하여 적용. 단, 최고지연배상금률은 연 11%</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>대출종류별 확정금리 적용 (단, 공단이 별도로 정하여 통보하는 경우 그에 따른다)- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%- 직업훈련생계비 : 연 1.0%- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%</etcRefSbjc>
<hdlInst>기업은행</hdlInst>
<cnpl>1566-2566</cnpl>
<rltSite>https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp?lncd=02&amp;grcd=21&amp;tmcd=209&amp;pdcd=0001&amp;wvcd=&amp;i_trns_biz_kncd=</rltSite>
<tgtFltr>근로자</tgtFltr>
<hdlInstDtlVw>기업은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>6</snq>
<finPrdNm>IBK청년전·월세대출 (전세)</finPrdNm>
<lnLmt>20000만원</lnLmt>
<irtCtg>고정금리, 변동금리</irtCtg>
<irt>3.8~4.3%</irt>
<maxTotLnTrm>3년</maxTotLnTrm>
<maxDfrmTrm>3년</maxDfrmTrm>
<maxRdptTrm>0년</maxRdptTrm>
<rdptMthd>만기일시상환</rdptMthd>
<usge>주거</usge>
<trgt>근로자, 사업자, 청년</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>IBK기업은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.</suprTgtDtlCond>
<age>34세 이하</age>
<incm>본인과 배우자의 합산 소득이 7천만원 이하인 자</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>1566-2566</rfrcCnpl>
<grnInst>한국주택금융공사</grnInst>
<jnMthd>영업점 방문</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)</lnIcdcst>
<ovItrYr>대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>- 근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 연 1.5%</etcRefSbjc>
<hdlInst>기업은행</hdlInst>
<cnpl>1566-2566</cnpl>
<rltSite>https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp</rltSite>
<tgtFltr>근로자, 사업자, 청년</tgtFltr>
<hdlInstDtlVw>기업은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>7</snq>
<finPrdNm>IBK청년전·월세대출 (월세)</finPrdNm>
<lnLmt>1200만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>4.34%</irt>
<maxTotLnTrm>11, 13년</maxTotLnTrm>
<maxDfrmTrm>8년</maxDfrmTrm>
<maxRdptTrm>3, 5년</maxRdptTrm>
<rdptMthd>원금균등분할상환</rdptMthd>
<usge>주거</usge>
<trgt>근로자, 사업자, 청년</trgt>
<instCtg>시중은행</instCtg>
<ofrInstNm>IBK기업은행</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>대출신청일 기준 만 34세 이하의 민법상 성년으로 무주택자인 세대주이며, 본인과 배우자의 합산 소득이 7천만원 이하인 자※ 개인신용평점에 따른 제한은 없으나 보증기관 내부 신용등급 등 기준에 충족하지 못할 경우 상품가입이 제한될 수 있습니다.</suprTgtDtlCond>
<age>34세 이하</age>
<incm>본인과 배우자의 합산 소득이 7천만원 이하인 자</incm>
<rsdArea>-</rsdArea>
<crdtSc>-</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>1566-2566</rfrcCnpl>
<grnInst>한국주택금융공사</grnInst>
<jnMthd>영업점 방문</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>5,000만원 초과 ~ 1억원 이하 인지세 70,000원 (고객부담 35,000원)1억원 초과 ~ 10억원 이하 인지세 150,000원 (고객부담 75,000원)</lnIcdcst>
<ovItrYr>대출이자율+연체가산금리 연 3% (최고 연체이자율 : 가계 및 중소기업의 경우 연 11%, 그 외 13%)</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>- 요양급여비 : 거치기간 연 0.6%, 상환기간 연 2.6%</etcRefSbjc>
<hdlInst>기업은행</hdlInst>
<cnpl>1566-2566</cnpl>
<rltSite>https://mybank.ibk.co.kr/uib/jsp/guest/ntr/ntr70/ntr7015/PNTR701500_i2.jsp</rltSite>
<tgtFltr>근로자, 사업자, 청년</tgtFltr>
<hdlInstDtlVw>기업은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>8</snq>
<finPrdNm>사잇돌Ⅱ대출_표준</finPrdNm>
<lnLmt>3000만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>~19.99%</irt>
<maxTotLnTrm>5(최대 60개월, 보증기간 이내)</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자, 사업자, 연금소득자</trgt>
<instCtg>민간기업</instCtg>
<ofrInstNm>SGI서울보증</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)</suprTgtDtlCond>
<age>없음</age>
<incm>(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397</rfrcCnpl>
<grnInst>SGI서울보증보험</grnInst>
<jnMthd>취급 금융기관 방문, 서금원 맞춤대출 조회</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>-</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>- 직업훈련생계비 : 연 1.0%</etcRefSbjc>
<hdlInst>저축은행</hdlInst>
<cnpl>취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397</cnpl>
<rltSite>https://www.fsb.or.kr/finloanconn_0100.act</rltSite>
<tgtFltr>근로자, 사업자, 연금소득자</tgtFltr>
<hdlInstDtlVw>취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>9</snq>
<finPrdNm>사잇돌Ⅱ대출_대환형</finPrdNm>
<lnLmt>2000만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>~19.99%</irt>
<maxTotLnTrm>5(최대 60개월, 보증기간 이내)</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>근로자, 사업자, 연금소득자</trgt>
<instCtg>민간기업</instCtg>
<ofrInstNm>SGI서울보증</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>중저신용 거래자로, 소득수준 요건 등에 해당하는 자 (개별 취급 금융기관 문의)</suprTgtDtlCond>
<age>없음</age>
<incm>(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397</rfrcCnpl>
<grnInst>SGI서울보증보험</grnInst>
<jnMthd>취급 금융기관 방문, 서금원 맞춤대출 조회</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>-</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>- 재직근로자의 대학학자금 : 거치기간 연 1.0%, 상환기간 연 3.0%</etcRefSbjc>
<hdlInst>저축은행</hdlInst>
<cnpl>취급 저축은행 콜센터, 서민금융콜센터 (국번없이) 1397</cnpl>
<rltSite>https://www.fsb.or.kr/finloanconn_0300.act</rltSite>
<tgtFltr>근로자, 사업자, 연금소득자</tgtFltr>
<hdlInstDtlVw>취급 저축은행(신한, 하나, KB, SBI, NH, 키움예스, 웰컴, 다올, 키움, BNK, 우리금융, 예가람, 융창)</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>상시</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
<item>
<basYm>202503</basYm>
<snq>10</snq>
<finPrdNm>사잇돌Ⅱ대출_채무조정졸업자</finPrdNm>
<lnLmt>1000만원</lnLmt>
<irtCtg>변동금리</irtCtg>
<irt>~19.99%</irt>
<maxTotLnTrm>5(최대 60개월, 보증기간 이내)</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원(리)금균등분할상환</rdptMthd>
<usge>생계</usge>
<trgt>채무조정자</trgt>
<instCtg>민간기업</instCtg>
<ofrInstNm>SGI서울보증</ofrInstNm>
<rsdAreaPamtEqltIstm>전국</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>- 소득수준 : 다음의 어느 하나에 해당하는 소득이 있는 자 - (근로소득)보증 신청일 현재 5개월 이상(유지) 재직자로서 연 소득이 12백만원 이상인 자 - (사업소득)보증 신청일 현재 4개월 이상(유지) 사업소득 발생자로서 연 소득이 6백만원 이상인 자 - (연금소득) 보증 신청일 현재 연금(국민연금, 공무원연금, 군인연금, 사학연금) 소득 1회 이상 수령자로서 연금 소득이 연 6백만원 이상인 자 -  기타조건 - 채무조정제도(개인워크아웃, 프리워크아웃, 개인회생)를 졸업한지 3년 이내인 자- 보험 청약일 현재 사잇돌 1, 2 대출’을 보유하고 있지 않은 자- 한국신용정보원을 통하여 확인되는 대부업체 대출보유건수가 1건 이내인 자</suprTgtDtlCond>
<age>없음</age>
<incm>(근로소득)5개월 이상 재직자 연 1,200만원 이상(사업소득)4개월 이상 사업소득 발생자이며 연 600만원 이상(연금소득)1회 이상 연금 수령자이며 연금소득 600만원 이상※중복소득 인정, 신청일 기준으로 계산</incm>
<rsdArea>-</rsdArea>
<crdtSc>없음</crdtSc>
<anin>-</anin>
<housHoldCnt>-</housHoldCnt>
<housAr>-</housAr>
<lnTgtHous>-</lnTgtHous>
<rfrcCnpl>033-370-2627</rfrcCnpl>
<grnInst>SGI서울보증보험</grnInst>
<jnMthd>취급 금융기관 방문, 서금원 맞춤대출 조회</jnMthd>
<rpymdCfe>없음</rpymdCfe>
<lnIcdcst>-</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>-</prftAddIrtCond>
<etcRefSbjc>-</etcRefSbjc>
<hdlInst>저축은행</hdlInst>
<cnpl>033-370-2627</cnpl>
<rltSite>https://www.fsb.or.kr/finloanconn_0400.act</rltSite>
<tgtFltr>채무조정자</tgtFltr>
<hdlInstDtlVw>취급저축은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc>-</cv19Rfrc>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg>-</cv19SuprCtg>
<cv19SuprCtn>-</cv19SuprCtn>
<cv19SuprTgtDtlCtn>-</cv19SuprTgtDtlCtn>
<mgmDln>기관 문의</mgmDln>
<prdCtg2>-</prdCtg2>
<fileWrtDt>202504010700</fileWrtDt>
</item>
</items>
</body>
</response>

setdefault를 이용해 xml의 tag명의 유일값 추출하기

In [23]:
tag_names = {}
for tags in soup.select("*"):
    tag_names.setdefault(tags.name, "")
for tag_name in tag_names.keys():
    print(tag_name)

response
header
resultCode
resultMsg
body
numOfRows
pageNo
totalCount
items
item
basYm
snq
finPrdNm
lnLmt
irtCtg
irt
maxTotLnTrm
maxDfrmTrm
maxRdptTrm
rdptMthd
usge
trgt
instCtg
ofrInstNm
rsdAreaPamtEqltIstm
suprTgtDtlCond
age
incm
rsdArea
crdtSc
anin
housHoldCnt
housAr
lnTgtHous
rfrcCnpl
grnInst
jnMthd
rpymdCfe
lnIcdcst
ovItrYr
prftAddIrtCond
etcRefSbjc
hdlInst
cnpl
rltSite
tgtFltr
hdlInstDtlVw
prdExisYn
cv19Rfrc
prdCtg
prdNm
cv19SuprCtg
cv19SuprCtn
cv19SuprTgtDtlCtn
mgmDln
prdCtg2
fileWrtDt

In [18]:
xml_result = {}
for item in soup.select("item"):
    for tags in item:
        if tags.name == None:
            continue
        else:
            xml_result.setdefault(tags.name, []).append(tags.text)
xml_result_df = pd.DataFrame(xml_result)
xml_result_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
5,202503,6,IBK청년전·월세대출 (전세),20000만원,"고정금리, 변동금리",3.8~4.3%,3년,3년,0년,만기일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
6,202503,7,IBK청년전·월세대출 (월세),1200만원,변동금리,4.34%,"11, 13년",8년,"3, 5년",원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
7,202503,8,사잇돌Ⅱ대출_표준,3000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
8,202503,9,사잇돌Ⅱ대출_대환형,2000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
9,202503,10,사잇돌Ⅱ대출_채무조정졸업자,1000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700

In [ ]:
numOfRows = int(soup.select_one("numOfRows").text)
totalCount = int(soup.select_one("totalCount").text)
total_pages = totalCount // numOfRows + 1

In [21]:
page = 1
xml_result_df_list = []
while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
    payload = dict(serviceKey=service_key, numOfRows=1000, pageNo=page, resultType="xml")
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.content
    soup = bs(response, 'xml')
    xml_result = {}
    for item in soup.select("item"):
        for tags in item:
            if tags.name == None:
                continue
            else:
                xml_result.setdefault(tags.name, []).append(tags.text)
    xml_result_df = pd.DataFrame(xml_result)
    xml_result_df_list.append(xml_result_df)
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_pages = totalCount // numOfRows + 1
    xml_result_df
    
    if page < total_page:
        page += 1
    else:
        break
    
xml_result_df_list = pd.concat(xml_result_df_list)
xml_result_df_list = xml_result_df_list.reset_index(drop=True)
xml_result_df_list

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=1&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=2&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=3&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=4&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=5&resultType=xml
200

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

# key_list를 만들고 select로 직접 추출하기

In [39]:
df_list = []
page = 1
while True:
    url = "https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    service_key = "iankTQz8XYq22YMuI1XI1FjJEU2Y/yM+cU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA=="
    payload = dict(serviceKey=service_key, numOfRows=1000, pageNo=page, resultType="xml")
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.content
    soup = bs(response, 'xml')
    numOfRows = int(soup.select_one("numOfRows").text)
    totalCount = int(soup.select_one("totalCount").text)
    total_page = totalCount // numOfRows + 1
    key_list = {}
    for item in soup.select("*"):
        key_list.setdefault(item.name, "")
    key_list = list(key_list.keys())
    keys = key_list[10:]
    result = {}
    for key in keys:
        for item in soup.select(key):
            result.setdefault(item.name, []).append(item.text)
    df_list.append(pd.DataFrame(result))

    if page < total_page:
        page += 1
    else:
        print("데이터 수집 완료")
        break
        
result_df = pd.concat(df_list)
result_df = result_df.reset_index(drop=True)
result_df

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=1&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=2&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=3&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=4&resultType=xml
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=iankTQz8XYq22YMuI1XI1FjJEU2Y%2FyM%2BcU8JNAWusfIrFtQHwzNvWJHqsHTXZnR9pQoO8z5AGRX2MDe0qTQerA%3D%3D&numOfRows=1000&pageNo=5&resultType=xml
200

In [43]:
result_df = pd.concat(df_list)
result_df = result_df.reset_index(drop=True)
result_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [ ]:
numOfRows = int(soup.select_one("numOfRows").text)
totalCount = int(soup.select_one("totalCount").text)
total_page = totalCount // numOfRows + 1

In [29]:
key_list = {}
for item in soup.select("*"):
    key_list.setdefault(item.name, "")
key_list = list(key_list.keys())
key_list

['response',
 'header',
 'resultCode',
 'resultMsg',
 'body',
 'numOfRows',
 'pageNo',
 'totalCount',
 'items',
 'item',
 'basYm',
 'snq',
 'finPrdNm',
 'lnLmt',
 'irtCtg',
 'irt',
 'maxTotLnTrm',
 'maxDfrmTrm',
 'maxRdptTrm',
 'rdptMthd',
 'usge',
 'trgt',
 'instCtg',
 'ofrInstNm',
 'rsdAreaPamtEqltIstm',
 'suprTgtDtlCond',
 'age',
 'incm',
 'rsdArea',
 'crdtSc',
 'anin',
 'housHoldCnt',
 'housAr',
 'lnTgtHous',
 'rfrcCnpl',
 'grnInst',
 'jnMthd',
 'rpymdCfe',
 'lnIcdcst',
 'ovItrYr',
 'prftAddIrtCond',
 'etcRefSbjc',
 'hdlInst',
 'cnpl',
 'rltSite',
 'tgtFltr',
 'hdlInstDtlVw',
 'prdExisYn',
 'cv19Rfrc',
 'prdCtg',
 'prdNm',
 'cv19SuprCtg',
 'cv19SuprCtn',
 'cv19SuprTgtDtlCtn',
 'mgmDln',
 'prdCtg2',
 'fileWrtDt']

In [32]:
keys = key_list[10:]
keys

['basYm',
 'snq',
 'finPrdNm',
 'lnLmt',
 'irtCtg',
 'irt',
 'maxTotLnTrm',
 'maxDfrmTrm',
 'maxRdptTrm',
 'rdptMthd',
 'usge',
 'trgt',
 'instCtg',
 'ofrInstNm',
 'rsdAreaPamtEqltIstm',
 'suprTgtDtlCond',
 'age',
 'incm',
 'rsdArea',
 'crdtSc',
 'anin',
 'housHoldCnt',
 'housAr',
 'lnTgtHous',
 'rfrcCnpl',
 'grnInst',
 'jnMthd',
 'rpymdCfe',
 'lnIcdcst',
 'ovItrYr',
 'prftAddIrtCond',
 'etcRefSbjc',
 'hdlInst',
 'cnpl',
 'rltSite',
 'tgtFltr',
 'hdlInstDtlVw',
 'prdExisYn',
 'cv19Rfrc',
 'prdCtg',
 'prdNm',
 'cv19SuprCtg',
 'cv19SuprCtn',
 'cv19SuprTgtDtlCtn',
 'mgmDln',
 'prdCtg2',
 'fileWrtDt']

In [33]:
soup.select("basYm")
soup.select("snq")

[<snq>1</snq>,
 <snq>2</snq>,
 <snq>3</snq>,
 <snq>4</snq>,
 <snq>5</snq>,
 <snq>6</snq>,
 <snq>7</snq>,
 <snq>8</snq>,
 <snq>9</snq>,
 <snq>10</snq>]

In [35]:
result = {}
for key in keys:
    for item in soup.select(key):
        result.setdefault(item.name, []).append(item.text)
df = pd.DataFrame(result)
df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
5,202503,6,IBK청년전·월세대출 (전세),20000만원,"고정금리, 변동금리",3.8~4.3%,3년,3년,0년,만기일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
6,202503,7,IBK청년전·월세대출 (월세),1200만원,변동금리,4.34%,"11, 13년",8년,"3, 5년",원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
7,202503,8,사잇돌Ⅱ대출_표준,3000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
8,202503,9,사잇돌Ⅱ대출_대환형,2000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
9,202503,10,사잇돌Ⅱ대출_채무조정졸업자,1000만원,변동금리,~19.99%,"5(최대 60개월, 보증기간 이내)",0년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700