# 정적 웹페이지 수집하기
* 순수 HTML, CSS로 만들어진 페이지
* javascript로 내용을 갱신하지 않는 페이지

# yes24 베스트셀러 자료 수집하기

In [3]:
import time
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

In [4]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
soup = bs(r.content, "lxml")
time.sleep(0.5)
# soup

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200

* 전체 yes24 베스트셀러 페이지 중 책 정보가 들어있는 곳: ul#yesBestList
* ul#yesBestList 아래의 li에 책 1권의 정보가 들어있음

In [5]:
# yes24 전체 페이지에서 책 정보가 들어있는 부분만 잘라서 book_list에 저장
book_list = soup.select("ul#yesBestList > li")

In [6]:
book_list

[<li class="" data-goods-no="144021119" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">1</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="단 한 번의 삶" border="0" class="lazy" data-original="https://image.yes24.com/goods/144021119/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(144021119); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">단 한 번의 삶</a>
 <span class="gd_feature">[ 양장 ]</span>
 <a class="bgYUI ico_nWin" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">단 한 번의 삶 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2598%2581%25ED%2595%2598&amp;authorNo=673&amp;author=김영하" target="">김영하</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b3%b5%eb%b3%b5%ec%84%9c%ea%b0%80&amp;query=%25EB%25B3%25B5%25EB%25B3%25B5%25EC%2584%259C%25EA%25B0%2580">복복서가</a></span>
 <span class="authPub info_date">2025년 04월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=257190">만년필용 노트+커버+스티커 세트/케이블 파우치(포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">15,120</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">16,800</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>840원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 242,073
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/144021119?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">15</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_9">리뷰 총점</span><em class="yes_b">8.8</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (3건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (12건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (0건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B8%25EC%2583%259D%25EC%259D%25B4%25EC%2595%25BC%25EA%25B8%25B0&amp;hashNm=%ec%9d%b8%ec%83%9d%ec%9d%b4%ec%95%bc%ea%b8%b0" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '인생이야기', '144021119','6696');">#인생이야기</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2582%25AC%25EC%259C%25A0%25EC%2599%2580%25EA%25B0%2590%25EC%2584%25B1&amp;hashNm=%ec%82%ac%ec%9c%a0%ec%99%80%ea%b0%90%ec%84%b1" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '사유와감성', '144021119','6832');">#사유와감성</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259E%2591%25EA%25B0%2580%25EC%259D%2598%25EC%2597%2590%25EC%2584%25B8%25EC%259D%25B4&amp;hashNm=%ec%9e%91%ea%b0%80%ec%9d%98%ec%97%90%ec%84%b8%ec%9d%b4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '작가의에세이', '144021119','2167');">#작가의에세이</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="txt"><a href="https://event.yes24.com/earlyReader?eventNo=257341">이달의 책 4월 : 독서 트래킹 포스터</a></span>
 <span class="date">(25.04.01 ~ 25.04.30)</span>
 </div>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="144021119" id="ordChk_144021119" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_144021119" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('144021119'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('144021119'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('144021119', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('144021119', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" onclick="order_payment.addMyListV3('144021119', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_144021119" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":144021119,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"단 한 번의 삶","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001034","goodsSortNm":"에세이","goodsAuth":"&lt;김영하&gt; 저","shopPrice":16800.00,"salePrice":15120.00,"discountShopPrice":1680.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="142876017" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">2</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="듀얼 브레인" border="0" class="lazy" data-original="https://image.yes24.com/goods/142876017/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(142876017); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); ">듀얼 브레인</a>
 <span class="gd_nameE">AI 시대의 실용적 생존 가이드</span>
 <a class="bgYUI ico_nWin" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">듀얼 브레인 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2584%25A0%2520%25EB%25AA%25B0%25EB%25A6%25AD&amp;authorNo=487104&amp;author=이선 몰릭" target="">이선 몰릭</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%258B%25A0%25EB%258F%2599%25EC%2588%2599&amp;authorNo=155164&amp;author=신동숙" target="">신동숙</a> 역
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%83%81%ec%83%81%ec%8a%a4%ed%80%98%ec%96%b4&amp;query=%25EC%2583%2581%25EC%2583%2581%25EC%258A%25A4%25ED%2580%2598%25EC%2596%25B4">상상스퀘어</a></span>
 <span class="authPub info_date">2025년 03월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/earlyReader?eventNo=257341">[이달의 책 4월] 독서 트래킹 포스터 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,900</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">21,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,050원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 265,344
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/142876017?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">38</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_9">리뷰 총점</span><em class="yes_b">8.7</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (11건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (26건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (1건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%259D%2598%25EC%259D%25BC%25EC%259E%2590%25EB%25A6%25AC&amp;hashNm=%eb%af%b8%eb%9e%98%ec%9d%98%ec%9d%bc%ec%9e%90%eb%a6%ac" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래의일자리', '142876017','3517');">#미래의일자리</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EB%25A5%25BC%25EA%25B7%25B8%25EB%25A6%25AC%25EB%258B%25A4&amp;hashNm=%eb%af%b8%eb%9e%98%eb%a5%bc%ea%b7%b8%eb%a6%ac%eb%8b%a4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래를그리다', '142876017','6691');">#미래를그리다</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%25A0%2584%25EB%259E%25B5&amp;hashNm=%eb%af%b8%eb%9e%98%ec%a0%84%eb%9e%b5" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래전략', '142876017','5290');">#미래전략</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=AI%25EA%25B4%2580%25EB%25A0%25A8%25EC%2584%259C&amp;hashNm=AI%ea%b4%80%eb%a0%a8%ec%84%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', 'AI관련서', '142876017','4492');">#AI관련서</a>
 </span>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/143587354">eBook <span class="relG_num">14,700원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="142876017" id="ordChk_142876017" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_142876017" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('142876017'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('142876017'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('142876017', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('142876017', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" onclick="order_payment.addMyListV3('142876017', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_142876017" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":142876017,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"듀얼 브레인","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001022","goodsSortNm":"자기계발","goodsAuth":"&lt;이선 몰릭&gt; 저/&lt;신동숙&gt; 역","shopPrice":21000.00,"salePrice":18900.00,"discountShopPrice":2100.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="142687238" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">3</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="어른의 품격을 채우는 100일 필사 노트" border="0" class="lazy" data-original="https://image.yes24.com/goods/142687238/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(142687238); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); ">어른의 품격을 채우는 100일 필사 노트</a>
 <span class="gd_feature">[ 양장 ]</span>
 <a class="bgYUI ico_nWin" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">어른의 품격을 채우는 100일 필사 노트 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A2%2585%25EC%259B%2590&amp;authorNo=135500&amp;author=김종원" target="">김종원</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b2%ad%eb%a6%bcLife&amp;query=%25EC%25B2%25AD%25EB%25A6%25BCLife">청림Life</a></span>
 <span class="authPub info_date">2025년 03월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=257553">[자기계발 기획] 아몬드 나무 명화 텀블러 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,000</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">20,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,000원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 176,877
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/142687238?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">56</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.9</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (37건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (19건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (0건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%2582%2598%25EB%25A5%25BC%25EC%259E%2583%25EC%25A7%2580%25EB%25A7%2588&amp;hashNm=%eb%82%98%eb%a5%bc%ec%9e%83%ec%a7%80%eb%a7%88" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '나를잃지마', '142687238','7493');">#나를잃지마</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2592%2588%25EA%25B2%25A9%25EC%259E%2588%25EB%258A%2594%25EC%2582%25B6&amp;hashNm=%ed%92%88%ea%b2%a9%ec%9e%88%eb%8a%94%ec%82%b6" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '품격있는삶', '142687238','7492');">#품격있는삶</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%2584%25EC%2582%25AC&amp;hashNm=%ed%95%84%ec%82%ac" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '필사', '142687238','7185');">#필사</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%2584%25EC%2582%25AC%25EC%2597%25B0%25EC%258A%25B5&amp;hashNm=%ed%95%84%ec%82%ac%ec%97%b0%ec%8a%b5" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '필사연습', '142687238','5514');">#필사연습</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="iconC"><em class="txt">기획전</em></span>

In [4]:
# for book in book_list:
#     print(book)
#     print()

In [4]:
result = {}
for idx, book in enumerate(book_list):
    print(f"{idx}/{len(book_list)} 추출 중", end="\r")
    # 책 제목
    book_title = book.select_one(".gd_name").text
    # 저자
    author = book.select_one(".info_row.info_pubGrp a").text
    # 출판사
    publisher = book.select_one(".authPub.info_pub a").text
    # 출간일
    date_pub = book.select_one(".authPub.info_date").text
    # 가격
    price = book.select_one(".info_row.info_price em.yes_b").text.replace(",", "")
    # 평점
    rating = book.select_one(".rating_grade em.yes_b").text if book.select_one(".rating_grade em.yes_b") != None else 0.0  
    # 리뷰 수
    n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text if book.select_one(".info_row.info_rating em.txC_blue") != None else 0  
    
    keys = ["book_title", "author", "publisher", "date_pub", "price", "rating", "n_reviews"]
    values = [book_title, author, publisher, date_pub, price, rating, n_reviews]
    for key, value in zip(keys, values):
        result.setdefault(key, []).append(value)
    
for key, value in result.items():
    print(key, len(value))
    
df = pd.DataFrame(result)
df

book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,15120,8.7,14
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,18900,8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,18000,9.9,56
3,소년이 온다,한강,창비,2014년 05월,13500,9.7,"3,848"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,17820,9.9,69
...,...,...,...,...,...,...,...
115,해커스 토익 RC Reading(리딩) 기본서,David Cho,해커스어학연구소,2023년 07월,16920,9.8,241
116,침묵의 퍼레이드,히가시노 게이고,재인,2025년 03월,19620,10.0,10
117,2025 시대에듀 투자자산운용사 실제유형 모의고사 + 특별부록 PASSCODE Pr...,유창호,시대고시기획 시대교육,2025년 03월,49500,10.0,2
118,마흔 고비에 꼭 만나야 할 장자,이길환,이든서재,2025년 04월,16920,0.0,0
119,마음을 읽는 아이 오로르,더글라스 케네디,밝은세상,2025년 03월,19800,10.0,22

In [5]:
print("가격:", len(list(soup.select("ul#yesBestList .info_row.info_price em.yes_b"))))
print("평점:", len(list(soup.select("ul#yesBestList .rating_grade em.yes_b"))))
print("리뷰 수:", len(list(soup.select("ul#yesBestList .info_row.info_rating em.txC_blue"))))

가격: 120
평점: 106
리뷰 수: 106

In [6]:
result['author']

['김영하',
 '이선 몰릭',
 '김종원',
 '한강',
 '김수미',
 '태수',
 '와야마 야마',
 '코이케 류노스케',
 '요시타케 신스케',
 '양귀자',
 '김주환',
 '유발 하라리',
 '유선경',
 '김주환',
 '최태성',
 '한강',
 '최태성',
 '안녕달',
 '백온유',
 '정대건',
 '브라이언 트레이시',
 '성해나',
 'ETS',
 '존 윌리엄스',
 'ETS',
 '오건영',
 '한강',
 '스즈키 유우토',
 '한현근',
 '정관 스님',
 '김지훈(포메뽀꼬)',
 '프리드리히 니체',
 '안-엘렌 클레르',
 '김직선',
 '한강',
 '김종원',
 '최태성',
 'David Cho',
 '김종원',
 '루리',
 '김종원',
 '천근아',
 '벤저민 하디',
 '김종원',
 '유설화',
 '이철희',
 '김지훤',
 '유은하',
 '박준',
 '네오쇼코',
 '네오쇼코',
 '신재은',
 '위혜정',
 '흔한남매',
 '태 킴',
 '타치바나 오레코',
 '아이다이로',
 '이어령',
 '알에스미디어',
 '백수린',
 '최승필',
 '한강',
 '클레어 키건',
 '정수봉',
 '해커스 일본어연구소',
 '한동훈',
 '손원평',
 '네빌 고다드',
 '세이노(SayNo)',
 '칼 에드워드 세이건',
 '유현준',
 '강용수',
 '타츠 유키노부',
 '강보라',
 '니이 사토루',
 '김종원',
 '조수용',
 '정주희',
 '문상훈',
 '고시넷 NCS 연구소',
 '김화요',
 '오창석',
 '유발 하라리',
 '리처드 도킨스',
 '최승호 외',
 '데일 카네기',
 '제시카 윤',
 '박태웅',
 '인이이',
 '하마지 아키',
 '최설희',
 '김민철',
 '이꽃님',
 '박진여',
 '김주환',
 '센바 쿠로노',
 '헤르만 헤세',
 '한강',
 '백유연',
 '하마지 아키',
 '모건 하우절',
 '엄예정',
 '강효미',
 '도야마 시게히코',
 '혼Job취업연구소',
 '김종우',
 '최진영',
 '슈뻘맨',
 '센딜 멀레이너선',
 '김지원',
 '한현근',
 '로이스 라우리',
 '모건 하우절',
 '카모시다 하지메',
 '카모시다 하지메',
 'David Cho',
 '히가시노 게이고',
 '유창호',
 '이길환',
 '더글라스 케네디']

In [7]:
result['author'][29]

'정관 스님'

In [8]:
# 저자 수
len(book_list[29].select(".authPub.info_auth a"))

4

In [9]:
book_list[29].select_one(".authPub.info_auth").text.split("/")[0]

'\n정관 스님, 후남 셀만 저'

In [10]:
book_list[29].select_one(".authPub.info_auth").text.split("/")[1]

'베로니크 회거 사진'

In [11]:
book_list[29].select_one(".authPub.info_auth").text.split("/")[2]

'양혜영 역\r\n                            '

In [12]:
book_list[18].select_one(".authPub.info_auth").text.split("/")[1].replace("\n", " ").strip("감추기 ")

'백온유 강보라 서장원 성해나 성혜령 이희주 현호정'

In [13]:
# 상세 페이지 링크
link = "https://www.yes24.com" + book_list[20].select_one(".gd_name")['href']
link

'https://www.yes24.com/product/goods/138282792'

# 전체 페이지 수집하기

* for 반복문

In [14]:
result_list = []
for page in range(1, 10):
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    soup = bs(r.content, "lxml")
    time.sleep(0.5)
    
    book_list = soup.select("ul#yesBestList > li")
    result = {}
    for idx, book in enumerate(book_list):
        print(f"{idx}/{len(book_list)} 추출 중", end="\r")
        # 책 제목
        book_title = book.select_one(".gd_name").text
        # 저자
        author = book.select_one(".info_row.info_pubGrp a").text
        # 출판사
        publisher = book.select_one(".authPub.info_pub a").text
        # 출간일
        date_pub = book.select_one(".authPub.info_date").text
        # 가격
        price = book.select_one(".info_row.info_price em.yes_b").text.replace(",", "")
        # 평점
        rating = book.select_one(".rating_grade em.yes_b").text if book.select_one(".rating_grade em.yes_b") != None else 0.0  
        # 리뷰 수
        n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text if book.select_one(".info_row.info_rating em.txC_blue") != None else 0  

        keys = ["book_title", "author", "publisher", "date_pub", "price", "rating", "n_reviews"]
        values = [book_title, author, publisher, date_pub, price, rating, n_reviews]
        
        for key, value in zip(keys, values):
            result.setdefault(key, []).append(value)
            
    result_list.append(pd.DataFrame(result))

result_list = pd.concat(result_list)
result_list = result_list.reset_index(drop=True)
result_list

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,15120,8.7,14
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,18900,8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,18000,9.9,56
3,소년이 온다,한강,창비,2014년 05월,13500,9.7,"3,848"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,17820,9.9,69
...,...,...,...,...,...,...,...
994,태도에 관하여 (20만 부 기념 완결판),임경선,토스트,2024년 09월,16200,9.3,33
995,장수탕 선녀님,백희나,스토리보울,2024년 04월,13500,9.8,24
996,중등 필독 신문,이현옥,체인지업,2024년 02월,16020,9.9,156
997,[예스리커버] 나는 나의 스무 살을 가장 존중한다,이하영,토네이도,2024년 08월,16200,9.4,212
998,컨셉 수업,호소다 다카히로,알에이치코리아(RHK),2024년 01월,19800,9.7,83

* while 반복문

In [15]:
result_list = []
page = 1
while True:
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    soup = bs(r.content, "lxml")
    time.sleep(5)
    # yes24 전체 페이지에서 책 정보가 들어있는 부분만 잘라서 book_list에 저장
    book_list = soup.select("ul#yesBestList > li")
    result = {}
    for idx, book in enumerate(book_list):
        print(f"{idx}/{len(book_list)} 추출중", end="\r")
        # 책 제목
        book_title = book.select_one(".gd_name").text
        # 저자
        author = book.select_one(".info_row.info_pubGrp a").text
        # 출판사
        publisher = book.select_one(".authPub.info_pub a").text
        # 출간일
        date_pub = book.select_one(".authPub.info_date").text
        # 가격
        price = book.select_one(".info_row.info_price em.yes_b").text
        # 평점
        rating = book.select_one(".rating_grade em.yes_b").text if book.select_one(".rating_grade em.yes_b") != None else 0.0
        # 리뷰수
        n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text if book.select_one(".info_row.info_rating em.txC_blue") != None else 0

        keys = ['book_title', 'author', 'publisher', 'date_pub', 'price', 'rating', 'n_reviews']
        values = [book_title, author, publisher, date_pub, price, rating, n_reviews]
        for key, value in zip(keys, values):
            result.setdefault(key, []).append(value)

    for key, value in result.items():
        print(key, len(value))

    result_list.append(pd.DataFrame(result))
    
    if page < 12:
        page += 1
    else:
        break
    
result_list = pd.concat(result_list)
result_list = result_list.reset_index(drop=True)
result_list

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200
book_title 39
author 39
publisher 39
date_pub 39
price 39
rating 39
n_reviews 39
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=10&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=11&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=12&pageSize=120
200

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,"15,120",8.7,14
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,"18,900",8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,"18,000",9.9,56
3,소년이 온다,한강,창비,2014년 05월,"13,500",9.7,"3,848"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,"17,820",9.9,69
...,...,...,...,...,...,...,...
994,태도에 관하여 (20만 부 기념 완결판),임경선,토스트,2024년 09월,"16,200",9.3,33
995,장수탕 선녀님,백희나,스토리보울,2024년 04월,"13,500",9.8,24
996,중등 필독 신문,이현옥,체인지업,2024년 02월,"16,020",9.9,156
997,[예스리커버] 나는 나의 스무 살을 가장 존중한다,이하영,토네이도,2024년 08월,"16,200",9.4,212
998,컨셉 수업,호소다 다카히로,알에이치코리아(RHK),2024년 01월,"19,800",9.7,83

# 저자, 역자, 글그림, 편저, 공동저자 등 구분하기

In [17]:
def text_clean(text):
    return text.replace("\n", " ").replace("\r", " ").strip()

In [28]:
def author_extraction(book):
    author = ""
    photo = ""
    trans = ""
    paint= ""
    for idx, item in enumerate(text_clean(book.select_one(".authPub.info_auth").text).split("/")):
        if idx == 0:
            if "저" == item[-1]:
                author = text_clean(item[:-2])
            elif "글" == item[-1]:
                author = text_clean(item[:-2])
            elif "글그림" == item[-3:]:
                author = text_clean(item[:-4])
        else:        
            if "정보 더 보기" == item[-7:]:
                author = text_clean(item.replace("정보 더 보기", ""))
            elif "사진" == item[-2:]:
                photo = text_clean(item[:-3])
            elif "역" == item[-1]:
                trans = text_clean(item[:-2])
            elif "글그림" == item[-3:]:
                paint = text_clean(item[:-4])
                
    print(f"author{author}, photo{photo}, trans{trans}, paint{paint}")
    return author, photo, trans, paint

In [29]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
soup = bs(r.content, "lxml")
time.sleep(0.5)
book_list = soup.select("ul#yesBestList > li")
for book in book_list[:2]:
    author, photo, trans, paint = author_extraction(book)
    print(author, photo, trans, paint)

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
author김영하, photo, trans, paint
김영하
author이선 몰릭, photo, trans신동숙, paint
이선 몰릭  신동숙

In [22]:
for item in text_clean(book_list[18].select_one(".authPub.info_auth").text).split("/"):
#     print(item)
    if "정보 더 보기" == item[-7:] :
        author = item.replace("정보 더 보기", "").strip()
        print(author)

백온유, 강보라, 서장원, 성해나, 성혜령 저 외 2명

In [23]:
for item in text_clean(book_list[18].select_one(".authPub.info_auth").text).split("/"):
#     print(item)
    if "감추기" in item[:4]:
        author = item.replace("감추기", "").strip()
        print(author)

백온유 강보라 서장원 성해나 성혜령 이희주 현호정